### ISSUE TITLE
[BUG] Заблокированные ресурсы не добавляются в ACL и не открываются

### ISSUE THREAD

**Issue by Evgeny252** [Anonym-tsk/nfqws-keenetic#10]
**Опишите проблему**
При добавлении вручную в  user.list недоступные провайдером домены по прежнему не работают (instagram.com, rutor.org, lostfilm.tv и подобные)
Не работает авто добавление в auto.list , он пустой. После 3-4 рестартов службы nfqws появился домен graph.facebook.com на который я не заходил и он также не доступен.

**Модель маршрутизатора**
 Giga (KN-1010) EAEU Версия ОС 4.1.7

**Провайдер**
Ростелеком , ethernet , тип подключения PPPoE

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
<# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="ppp0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
>
```

`ps | grep nfqws`
```
<~ # ps | grep nfqws
 9615 21474836   488 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/opt/var/run/nfqws.p
11605 root      5400 S    grep nfqws
>
```

`iptables-save | grep 200`
```
<~ # iptables-save | grep 200
-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A _NDM_IP_PROTECT -p tcp -m tcp --dport 8200 -j _NDM_SL_PROTECT
>
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
<~ # sysctl net.netfilter.nf_conntrack_checksum
net.netfilter.nf_conntrack_checksum = 1
>
```

**Comment by Anonym-tsk** [comment]
1. Пожалуйста, переустановите nfqws скрипты
2. Попробуйте в конфиге заменить `--dpi-desync-fooling=md5sig` на `--dpi-desync-fooling=badsig,md5sig` и перезапустить сервис
3. Выключите IPv6 на интерфейсе провайдера 
4. Проверьте, не используются ли у вас контентные фильтры типа NextDNS
5. Проверьте, что вы используете публичный DNS, а не провайдера

**Comment by Evgeny252** [comment]
Выполнил все рекомендации.
Приложил скрины, для наглядности, наименования соответствующие:

![uninstall](https://github.com/user-attachments/assets/24084e92-8536-4dfc-ac66-1fa2c7b192bc)
![install](https://github.com/user-attachments/assets/cb3cd9d0-0ee2-43bb-a944-abd4a5b234d9)
![config](https://github.com/user-attachments/assets/a6a1002e-0de7-4548-959f-e33f1713342f)
![ipv6_disable](https://github.com/user-attachments/assets/1ba63f58-7167-4c81-b14f-531f6e41c061)
![ipv6_disable_2](https://github.com/user-attachments/assets/bed2a7a3-476e-445f-9af0-81a4bbf4836f)

**Comment by Anonym-tsk** [comment]
Попробуйте удалить Adguard dns из ppp подключения и настроить в разделе интернет-фильтры гугл днс

**Comment by Anonym-tsk** [comment]
Ну и в разделе ppp тоже игнорировать днс поставить надо

**Comment by Evgeny252** [comment]
сейчас попробую, но у моего коллеги, с точно таким же роутером и аддгуард DNS все работает , только провайдер у него Билайн

**Comment by Anonym-tsk** [comment]
Провайдеры разные. Возможно, ваш блочит по DNS, а его нет

**Comment by Evgeny252** [comment]
поставил галку, также сделал google dns 8.8.8.8 и 8.8.4.4 , итог на телефоне перестал нормально работать ютуб, инста не открывается также, файлы auto.list и usrs.list по прежнему не работают 
Обратил внимание, что все сломалось после того , как я поставил галку Игнорировать DNS в разделе ppp 
![изображение](https://github.com/user-attachments/assets/ad59c469-dcd5-41dd-a190-bfe85152c027)

**Comment by Evgeny252** [comment]
стоп, я не там удалил DNS..

**Comment by Evgeny252** [comment]
все поменял, с гугл DNS не работает вообще ничего ) я про ютубе, и любой другой сайт забаненный РКН

**Comment by Evgeny252** [comment]
итого, откатил все в зад, на дефолт, работает на телефоне инста и другие ресурсы, на ПК работает ютуб, но не открывается инста.. такие дела..

**Comment by Evgeny252** [comment]
попробовал режим All , на нем также, на компе не работает, на телефоне заработало

**Comment by Anonym-tsk** [comment]
Так может у вас на компе проблема? Посмотрите что он по DHCP получает. Отключите от сети и подключите снова.

**Comment by Anonym-tsk** [comment]
Ну как, решилась проблема или что-то еще не работает?

**Comment by Evgeny252** [comment]
ну по факту, auto.list и users.list как не работали так и не работают
ютуб +- работает, почему +- потому что в отличие от предыдущего решения (goodbyeDOUI у меня присутствуют периодические подгрузки во время просмотра

**Comment by Anonym-tsk** [comment]
Вчера добавил поддержку QUIC, кто-то отписал, что инста заработала. Можете попробовать обновить.

**Comment by Evgeny252** [comment]
как обновить без удаления?

**Comment by Anonym-tsk** [comment]
> как обновить без удаления?

Просто запустите еще раз установку. Инсталлер предложит сохранить старые списки, если они вам нужны

**Comment by Evgeny252** [comment]
а есть понимание , почему на мобильном устройстве ютуб постоянно тупит и подгружает контент?

**Comment by Anonym-tsk** [comment]
Понимание есть. Попробуйте подобрать параметры nfqws, которые будут работать с вашим провайдером.

**Comment by Evgeny252** [comment]
мы  с вами пробовали по вашей рекомендации в конфиге менять вот это:
Попробуйте в конфиге заменить --dpi-desync-fooling=md5sig на --dpi-desync-fooling=badsig,md5sig и перезапустить сервис

при изменение с варианта по умолчанию, становится гораздо хуже

**Comment by Anonym-tsk** [comment]
Скачайте на компьютер zapret и выполните blockcheck скрипт, возможно он подскажет подходящие параметры

**Comment by NijazKa** [comment]
можно попробовать добавить DNS over TLS
![2024-08-21_10-59-12](https://github.com/user-attachments/assets/3ac02e6f-797b-4fc5-afd9-c449b9d1ffc0)

**Comment by Evgeny252** [comment]
вам это помогло ? у меня до сих пор ютуб на телефоне работает очень плохо =( постоянно подгрузки и тд, только на ПК работает нормально

**Comment by Evgeny252** [comment]
я выполнил рекомендации, не помогло. Есть ли какие то идеи/предложения как починить ютуб на мобильных устройствах?

**Comment by Anonym-tsk** [comment]
Предлагаю продолжить в чате, ссылка на главной странице

**Comment by Evgeny252** [comment]
я чет не пойму где =(  
![изображение](https://github.com/user-attachments/assets/f9bb92d3-7fb6-4c4f-b21e-3c86d575eff9)

**Comment by Anonym-tsk** [comment]
https://t.me/nfqws

**Comment by Evgeny252** [comment]
я зашел, потом перешел по ссылке как там указано и меня кикнуло и теперь не дает вступить в группу повторно
![изображение](https://github.com/user-attachments/assets/dab36e1f-9a07-4637-8ebd-e800e8412a29)

**Comment by Anonym-tsk** [comment]
Попробуйте ещё раз, провел амнистию

**Comment by Evgeny252** [comment]
хз, не заходит на ваш канал в тг, пишет запрещено, у меня сломался скрипт , я не могу зайти на роутер по 222 порту как указано в инструкции по установки, не подскажете почему?
Тормоза ютуба на мобильном не придумали как побеждать?
