### ISSUE TITLE
[BUG] Web, ошибка авторизации

### ISSUE THREAD

**Issue by Omn1z** [Anonym-tsk/nfqws-keenetic#102]
После обновления с добавлением авторизации, не авторизовывает, можно ли как то сделать так чтобы авторизация была опциональная через конфиг?
![{C65D61BF-EE5E-49E2-AC48-9026B900C4E6}](https://github.com/user-attachments/assets/ff518835-dfa3-469a-b7b6-ca93ad54efab)

**Comment by Anonym-tsk** [comment]
Логин и пароль ввести пробовали?

**Comment by Omn1z** [comment]
> Логин и пароль ввести пробовали?

UPD, Не увидел что логин и пароль от entware, вводил от панели роутера 😂

**Comment by Omn1z** [comment]
![{C9A69CD3-BDF2-4D5E-99A3-CB9147F1C741}](https://github.com/user-attachments/assets/16ac8b35-2b2b-4a97-a8b2-f08634ee6caf)

**Comment by Anonym-tsk** [comment]
Это браузерный кэш, уже исправлено.
Нажмите Ctrl+R
