### ISSUE TITLE
[BUG] Не запускается сервис No chain/target/match by that name

### ISSUE THREAD

**Issue by Sergmasharov** [Anonym-tsk/nfqws-keenetic#11]
После установки не запускается сервис. У меня два провайдера ppp0 ppp1
iptables: No chain/target/match by that name.

**Модель маршрутизатора**
Keenetic Giga 4.1.7

**Провайдер**
У меня два провайдера ppp0 ppp1

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
ppp0 ppp1
режим auto
настройки по умолчанию
```

`ps | grep nfqws`
```
11319 root      5400 S    grep nfqw
```

`iptables-save | grep 200`
```
ничего нет, в этом то и проблема
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by Anonym-tsk** [comment]
Через web-интерфейс Keenetic установить пакеты Протокол IPv6 и Модули ядра подсистемы Netfilter.

**Comment by Sergmasharov** [comment]
Установлено

**Comment by Anonym-tsk** [comment]
Ошибка говорит обратное. Покажите скриншот.

**Comment by Sergmasharov** [comment]
Прошу прощения. Проглазел netfilter... Спасибо!
