### ISSUE TITLE
[Feature request] Поддержка роутеров TP-Link Deco

### ISSUE THREAD

**Issue by SVY76** [Anonym-tsk/nfqws-keenetic#112]
Вроде бы у них когда-то был открыт 22 порт, но сейчас через него разрешено ходить только их приложению.
Есть несколько знакомых, у которых дома на Deco меш-сеть построена, конечно же, никто не хочет морочиться с переходом на Кинетики.
Было бы классно, чтобы nfqws существовал и для этих роутеров.

**Comment by unameras** [comment]
Вроде они поддерживают OpenWRT, прошить и ставить nfqws

**Comment by Anonym-tsk** [comment]
Если там есть entware, все и так будет работать.
Если нет, то ничем не помочь.
