### ISSUE TITLE
[Feature request] Отдельные файлы по группам доменов

### ISSUE THREAD

**Issue by unixty** [Anonym-tsk/nfqws-keenetic#114]
**Подробно опишите проблему**
Сделать так, чтоб можно было добавлять отдельными файлами списки доменов, разделенных на группы

**Какое решение вы предлагаете?**
[ссылка из обсуждения в zapret](https://github.com/bol-van/zapret/discussions/475)

**Comment by Anonym-tsk** [comment]
Вы и сейчас можете использовать отдельные файлы, например так
```
NFQWS_ARGS="--dpi-desync=split2 --hostlist=user1.list --new --dpi-desync=disorder2 --hostlist=user2.list --new --dpi-desync=split2,fake --dpi-desync-fooling=md5sig,badseq"
```
