### ISSUE TITLE
[BUG] Не запускается Web

### ISSUE THREAD

**Issue by Mechanicsu** [Anonym-tsk/nfqws-keenetic#118]
После перехода на v2.5.11 на Keenetic не стартует nfqws-keenetic-web.
Выявил причину - переход на lighttpd, а он используется в ndm для сервиса WebDAV.
Полечил костылем: в /opt/etc/init.d/S80lighttpd  изменил PROCS=lighttpd на PROCS=lighttpd-entw
и переименовал /opt/sbin/lighttpd на /opt/sbin/lighttpd-entw

**Comment by Anonym-tsk** [comment]
Исправлено в entware (https://github.com/Entware/entware-packages/pull/27) и в nfqws-keenetic (в следующей версии)

**Comment by ryzhovau** [comment]
Оно как-то странно исправлено. То ли скрипт не использует PATH, то ли интерактивный сеанс пользователя уже запомнил прежнее расположение lighttpd.

**Comment by avpxz** [comment]
костыль в виде указания PROCS=/opt/sbin/lighttpd
ломает выдачу S80lighttpd check
пишет dead (на асусе)

**Comment by ryzhovau** [comment]
Тогда однозначно сработает костыль из первого поста.

**Comment by avpxz** [comment]
Сработает, но после обновления пакета вернется как было) поэтому на асусе проще написать PROCS=lighttpd
