### ISSUE TITLE
[BUG] Не решило проблему загрузки видео на Youtube

### ISSUE THREAD

**Issue by Nope-enough** [Anonym-tsk/nfqws-keenetic#12]
**Опишите проблему**
Установил, сам сайт Youtube грузит, грузит даже заблокированные провайдером сайты (Fb. Instagram), однако видео не запускает (бесконечная загрузка)
Что попробовал: сетевое ускорение убрал, IPV6 отключил, DoT/DoH настроил, провайдерский DNS отключен, сторонних DNS не присутствует, UDP трафик пробовал блочить - не помогло

**Модель маршрутизатора**
Keenetic Viva (KN-1910), прошивка 4.1.7

**Провайдер**
Телекор. Подключение автоматическое (DHCP)

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="eth3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Try different variants, e.g. `--dpi-desync-fooling=badsum` or `--dpi-desync-fooling=md5sig,badsum`
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
```

`ps | grep nfqws`
```
8033 21474836   480 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/opt/var/run/nfqws.pid --dpi-desync=fake disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig --hostlist
 8718 root      5400 S    grep nfqws
```

`iptables-save | grep 200`
```
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by Nope-enough** [comment]
Добавлю что поведение одинаковое на всех устройствах - ПК, iOS, LG

**Comment by Anonym-tsk** [comment]
Можно попробовать заблокировать QUIC вообще

Создаём в веб-интерфейсе роутера правило файерволла, блокирующее протокол QUIC:
Межсетевой экран → Домашняя сеть → Добавить правило
Включить правило: Включено
Описание: Блокировать QUIC
Действие: Запретить
Протокол: UDP
Номер порта назначения: Равен 443
Остальные параметры оставляем без изменений

**Comment by Nope-enough** [comment]
Пробовал - не помогло

**Comment by Nope-enough** [comment]
Проблема очень похожа на ту, что была с goodbyedpi - сам сайт YT отлично загружается, но в момент запуска видео загрузить данные не может. На goodbyedpi предлагалось решать проблему через блокировку доменов провайдера, но я пока не понял как это сделать на уровне роутера

**Comment by Nope-enough** [comment]
Проблема очень похожа на ту, что была с goodbyedpi - сам сайт YT отлично загружается, но в момент запуска видео загрузить данные не может. На goodbyedpi предлагалось решать проблему через блокировку доменов провайдера, но я пока не понял как это сделать на уровне роутера

**Comment by Anonym-tsk** [comment]
В браузере нажмите F12, перейдите на вкладку Network, и откройте видео на ютубе. Приложите скриншот

**Comment by Nope-enough** [comment]
Проблема сама пропала, видео стало грузится
Ничего не менял
Сейчас все ок

**Comment by Nope-enough** [comment]
Снова вернулась проблема
![image](https://github.com/user-attachments/assets/96b4ed1c-1248-4020-b392-3b29b37fe05a)

**Comment by Nope-enough** [comment]
Через 30 сек - минуту ожидания видео начинает воспроизводится

**Comment by Anonym-tsk** [comment]
Давно обновляли? Вчера поддержку QUIC добавил. Может поможет.

**Comment by Nope-enough** [comment]
Только что вот обновил, не полечило

**Comment by Anonym-tsk** [comment]
А сломались все домены конкретно Ютуб?

**Comment by Nope-enough** [comment]
Сам ютуб открывается как и раньше нормально
Ломается в момент воспроизведения любого видео - оно просто крутится 1-2 минуты, потом запускается в низком качестве
С включенным VPN такой проблемы нет

**Comment by Anonym-tsk** [comment]
Могу предложить только попробовать разные параметры nfqws, почитайте на странице автора, может подберёте под себя. Кажется, это особенность вашего провайдера.

**Comment by massarakh** [comment]
Аналогичная проблема, перепробовал массу вариантов параметров nfqws и так и не заработал именно просмотр видео. В остальном, YouTube грузится мгновенно. Роутер Keenetic Ultra KN-1811.

**Comment by Nope-enough** [comment]
Попробовал переустановить с модом auto
1. Youtube - часть видео стало загружаться с небольшим лагом, но грузит не 100% видео. По ощущениям процентов 60 все еще виснет
2. auto.list - не добавляет автоматом (в tqws работало сильно лучше). Пришлось руками добавлять facebook, instagram. Последний при этом не завелся, а на all работал отлично

**Comment by Nope-enough** [comment]
Инстаграм полетел после того как добавил домены в user.list 
cdninstagram.com
ig.me
А еще может быть неочевидно что нужно делать reload скрипта при изменении списков

**Comment by yudaev-valery** [comment]
сегодня проблема повторилась

**Comment by demonixid** [comment]
сегодня опять отвалился ютуб на последней версии nfqws.
Помогло добавить в правила `--dpi-desync=split2 --dpi-desync-split-seqovl=1`

**Comment by AlxSmv** [comment]
> сегодня опять отвалился ютуб на последней версии nfqws. Помогло добавить в правила `--dpi-desync=split2 --dpi-desync-split-seqovl=1`

Спасибо Вам огромное тоже помогло, оператор МТС

**Comment by AlexandrKonev** [comment]
> сегодня опять отвалился ютуб на последней версии nfqws. Помогло добавить в правила `--dpi-desync=split2 --dpi-desync-split-seqovl=1`

Спасибо! Мне тоже помогло. В итоге вот такая строка получается:
NFQWS_ARGS="--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badseq --wssize=1:6 --dpi-desync=split2 --dpi-desync-split-seqovl=1"
