### ISSUE TITLE
Маршрутизация/NAT offloading

### ISSUE THREAD

**Issue by Vasabiko** [Anonym-tsk/nfqws-keenetic#126]
Приветствую, прошивка Openwrt 23xxxx. Режется в 2 раза скорость тарифа, при выключенной этой функции. При включении, скорость по тарифу, но соответственно ломается  обход ( подключение идёт через nfqws). Читал в мануале про неё, но не нашёл что надо прописать, чтобы всё работало?

**Comment by Anonym-tsk** [comment]
А какое отношение это имеет к NFQWS? У вас роутер не умеет маршрутизировать быстро без этой опции.
