### ISSUE TITLE
[BUG] Ошибка в описании?

### ISSUE THREAD

**Issue by dim5x** [Anonym-tsk/nfqws-keenetic#128]
**Опишите проблему**
В [Полезное](https://github.com/Anonym-tsk/nfqws-keenetic?tab=readme-ov-file#%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D0%BE%D0%B5), пункт 2:

> Скрипт запуска/остановки /opt/etc/init.d/`S51nfqws`{start|stop|restart|reload|status}

Такого файла нет: S51nfqws, есть nfqws-keenetic .

```
root@OpenWrt:~# ls /etc/init.d/
boot             firewall         network          sysctl           uhttpd
cron             gpio_switch      nfqws-keenetic   sysfixtime       umount
dnsmasq          led              odhcpd           sysntpd          urandom_seed
done             lighttpd         packet_steering  system           urngd
dropbear         log              rpcd             ucitrack
```
**Модель маршрутизатора**
OpenWRT на виртуальном роутере.

**Comment by dim5x** [comment]
Спасибо за полезный комментарий.

**Comment by Anonym-tsk** [comment]
![Screenshot_20241117-233634](https://github.com/user-attachments/assets/193ad7f2-677c-45c1-80c2-014ad67a9602)

**Comment by dim5x** [comment]
Я это прочёл: и искал не в /opt,  а в /etc/init.d/.
И про остановку / запуск тоже прочёл.

Так как Полезное идёт в общем списке, а не применительно только к кинетику, я предположил что оно относится и к OpenWRT - отсюда и возник вопрос, что возможно опечатка, т.к. в одном месте указано S51nfqws, а в другом: nfqws-keenetic.
Я не подумал что сервис запускается разными командами.
