### ISSUE TITLE
[BUG] Web интерфейс пустой

### ISSUE THREAD

**Issue by oompaloomp** [Anonym-tsk/nfqws-keenetic#129]
Web интерфейс пустой. Нет запроса авторизации, сразу открывается такой:
![image](https://github.com/user-attachments/assets/b9e4c892-0375-42db-b34c-1f94bc4beae6)
В response index.php - No input file specified.
Переустановка не помогает.
Роутер Keenetic Hopper DSL -KN-3610.
Версия nfqws-keenetic 2.5.12

**Comment by LordSlon** [comment]
Больше никто не жалуется. Попробуй очистить кэш/сбросить кэш dns/отключить прокси и vpn/сменить браузер

**Comment by Anonym-tsk** [comment]
Я предлагаю вам очистить флешку и установить entware заново

**Comment by chex01** [comment]
![Screenshot_2024-12-01-00-21-40-418_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/78cbd9e1-9ab4-4a67-a7d9-34aca3566a96)

Переустановка не помогает.
Роутер Keenetic Ultra KN-1811.
Версия nfqws-keenetic 2.6.3

**Comment by chex01** [comment]
![Screenshot_2024-12-01-20-18-25-303_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/0d1e56e3-1d21-45b1-952f-5b2b4c0f8dae)

Проблема появилась после редактирования файла /opt/etc/php.ini.

В общем чтобы заработало сделал так:
```
opkg remove --autoremove nfqws-keenetic-web
rm /opt/etc/php.ini
rm /opt/etc/php.ini-opkg
opkg install nfqws-keenetic-web
```

**Comment by butaford** [comment]
Попробуйте отредактировать /opt/etc/php.ini:
Закоментируйте параметр:
`;doc_root = "/opt/share/www"`
и раскоментируйте и поставьте значение в 0
`cgi.force_redirect = 0`
