### ISSUE TITLE
[BUG] не ставиться пакет. С tpws проблем нет.

### ISSUE THREAD

**Issue by demonixid** [Anonym-tsk/nfqws-keenetic#13]
**Опишите проблему**
Не запускается процесс пакета
tpws ставится и запускается без проблем
Пробовал чистую установку с голым entware

**Модель маршрутизатора**

Hopper (KN-3810) 4.1.7

**Провайдер**
ethernet

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
<
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="eth2.2"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Try different variants, e.g. `--dpi-desync-fooling=badsum` or `--dpi-desync-fooling=md5sig,badsum`
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log>

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
>
```

`ps | grep nfqws`
```
<5090 root      5400 S    grep nfqws>
```

`iptables-save | grep 200`
```
<нет выдачи>
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
<net.netfilter.nf_conntrack_checksum = 0>
```

**Comment by demonixid** [comment]
`**/opt/etc/init.d/S51nfqws start**
sh: can't kill pid 3870: No such process
xt_multiport.ko loaded
xt_NFQUEUE.ko loaded
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 2 hosts from /opt/etc/nfqws/exclude.list
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
Started NFQWS service
~ # **/opt/etc/init.d/S51nfqws status**
sh: can't kill pid 5681: No such process
Service NFQWS is stopped
`

**Comment by demonixid** [comment]
`/opt/etc/init.d/S51nfqws restart`
```
<sh: can't kill pid 2564: No such process
Service NFQWS is not running
sh: can't kill pid 2564: No such process
xt_multiport.ko loaded
xt_NFQUEUE.ko loaded
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 2 hosts from /opt/etc/nfqws/exclude.list
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
Started NFQWS service
>
```

**Comment by Anonym-tsk** [comment]
Через web-интерфейс Keenetic установить пакеты Протокол IPv6 и Модули ядра подсистемы Netfilter.
Об этом написано в инструкции.

**Comment by demonixid** [comment]
Да вы правы, я был уверен, что он установлен, так как до этого ставил nfqws (по старой инструкции) в ручную и там был. Все запустилось спасибо.
