### ISSUE TITLE
openwrt обновился с opkg до apk - репозиторий не работает

### ISSUE THREAD

**Issue by deadcxap** [Anonym-tsk/nfqws-keenetic#133]
в связи с переходом openwrt на пакетный менеджер apk - выпилили как opkg из текущих прошивок, так и изменили репозитории (из-за чего даже на старых версиях сейчас невозможно что-либо скачать/установить). формат пакета тоже поменялся с .ipk на .apk - и новый пакетный менеджер старые пакеты ставить не умеет совсем.
за сим прошу обновить репозиторий, или сделать дубль для новой версии.

второй вопрос: есть iptables-nft, возможно ли его использовать как альтернативу удалению nftables?

заранее спасибо.

**Comment by Anonym-tsk** [comment]
Имею в виртуалке OpenWRT 23.05.5. Не вижу, чтобы использовался apk.
На офсайте OpenWRT страница по apk почти пустая.
Откуда информация?

**Comment by Anonym-tsk** [comment]
На 24.10.0-rc2 аналогично, opkg никуда не делся

**Comment by deadcxap** [comment]
https://www.opennet.ru/opennews/art.shtml?num=62240
Ставили на роутер dlink dir-2150 openwrt, сперва старую версию около пары месяцев давности - opkg даже не делает update, в репе уже лежат apk.
Обновили на актуальную версию - opkg нет в прошивке, apk add opkg говорит что такого пакета нет.

**Comment by Anonym-tsk** [comment]
В версии [2.7.1](https://github.com/Anonym-tsk/nfqws-keenetic/releases/tag/v2.7.1) добавлена поддержка ([инструкция по установке](https://github.com/Anonym-tsk/nfqws-keenetic?tab=readme-ov-file#%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D0%B8-25xx-%D0%B8-snapshot-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BD%D1%8B%D0%B9-%D0%BC%D0%B5%D0%BD%D0%B5%D0%B4%D0%B6%D0%B5%D1%80-apk))
