### ISSUE TITLE
[BUG] AHL не заполняется. В режиме All все работает.

### ISSUE THREAD

**Issue by Whishp** [Anonym-tsk/nfqws-keenetic#14]
**Опишите проблему**
AHL не заполняется. В режиме All все работает.

**Модель маршрутизатора**
GIGA AX  4.1.7

**Провайдер**
Телесети, подключение ethernet

**Выполните команды и приложите их вывод**
`/opt/etc/init.d/S51nfqws restart`
```
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 2 hosts from /opt/etc/nfqws/exclude.list
Started NFQWS service

```

`cat /opt/etc/nfqws/nfqws.conf`
```
ISP_INTERFACE="eth3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Try different variants, e.g. `--dpi-desync-fooling=badsum` or `--dpi-desync-fooling=md5sig,badsum`
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
```

`ps | grep nfqws`
```
 2721 21474836   484 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/op
 2742 root      5400 S    grep nfqws
```

`iptables-save | grep 200`
```
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by Anonym-tsk** [comment]
Приложите лог `/opt/var/log/nfqws.log`

**Comment by Whishp** [comment]
Он пустой

**Comment by Anonym-tsk** [comment]
Покажите вывод `ip addr show`

**Comment by Whishp** [comment]
https://gist.github.com/Whishp/2cd001b6bab07bd10e767192aaf58c67

**Comment by Whishp** [comment]
В лог в итоге что-то добавляется. Но не те сайты, на которые захожу.
[nfqws.log](https://github.com/user-attachments/files/16611952/nfqws.log)

**Comment by Anonym-tsk** [comment]
Значит трафик всё-таки обрабатывается.
В авто список должен точно уже добавиться googleads.g.doubleclick.net
Какой днс у вас используется на компьютере?

**Comment by Whishp** [comment]
Все что в user list добавлено-работает. DNS DoT google.

**Comment by Anonym-tsk** [comment]
Ну смотрите, трафик обрабатывается, nfqws работает, домены добавляются.
Какие конкретно домены у вас не работают и при этом не отображаются в логе?

**Comment by Whishp** [comment]
Любые недоступные, которые не добавлены в user list. Доменов двадцать проверил.

**Comment by Whishp** [comment]
Только что удалил и установил tpws, сразу все открываются и добавляется домены в auto list. Поставил обратно и снова тишина.

**Comment by Anonym-tsk** [comment]
При попытке открыть недоступный домен, в логе что-то появляется?

**Comment by Anonym-tsk** [comment]
Попробуйте в конфиге изменить параметр на `--dpi-desync-fooling=badsum`

**Comment by Whishp** [comment]
> При попытке открыть недоступный домен, в логе что-то появляется?

Абсолютно пусто по этим доменам.

**Comment by Whishp** [comment]
> Попробуйте в конфиге изменить параметр на `--dpi-desync-fooling=badsum`

Спасибо. Вечером попробую.

**Comment by Whishp** [comment]
> Попробуйте в конфиге изменить параметр на `--dpi-desync-fooling=badsum`

Не помогло.

**Comment by Anonym-tsk** [comment]
Покажите скриншот настроек сети на компьютере, интересует раздел dns

**Comment by Whishp** [comment]
> Покажите скриншот настроек сети на компьютере, интересует раздел dns

![Снимок экрана 2024-08-14 180031](https://github.com/user-attachments/assets/c994a522-c840-44d0-9db2-83994dc327e3)

**Comment by Anonym-tsk** [comment]
Приведите пример хотя бы одного сайта. Возможно он блокируется по ip и ничего с этим не поделать

**Comment by Whishp** [comment]
> Приведите пример хотя бы одного сайта. Возможно он блокируется по ip и ничего с этим не поделать
Twitter, instagram, facebook

**Comment by Whishp** [comment]
> Приведите пример хотя бы одного сайта. Возможно он блокируется по ip и ничего с этим не поделать

Twitter, Instagram, Facebook, В режиме ALL или List они все работают.

**Comment by Whishp** [comment]
Поставил оригинальный zapret - все работает в авто режиме.

**Comment by Anonym-tsk** [comment]
Учитывая, что nfqws - это бинарник из оригинального zapret, я даже не знаю что могло пойти не так
