### ISSUE TITLE
Не могу зайти на web морду 

### ISSUE THREAD

**Issue by Kotangens89** [Anonym-tsk/nfqws-keenetic#145]
Не могу зайти в настройки по адресу http://192.168.1.1:90
Роутер xiaomi mi3. 
Всё работает но доступа у настройкам по http://192.168.1.1:90
По SSH пишет что всё установлено

**Comment by etiterin** [comment]
Скорее всего у вас rtorrent установлен или еще что-то, что использует lighttpd, и настройки конфликтуют. Там немного с бубном сплясать нужно, чтобы оно вместе работало
