### ISSUE TITLE
WebOS за роутером.

### ISSUE THREAD

**Issue by bor2121** [Anonym-tsk/nfqws-keenetic#15]
Спасибо все отлично встало на Ultra. Заработало везде: яблоки, андроиды, Андроид-приставка, компьютеры...  но я не проверил на телевизорах, вчера дети озадачили. Действительно  приложения Ютуб на WebOS открывается по несколько минут, а если открылось то контент дергается.
Нет ли вариантов? 
в конфиге сейчас так:
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="eth3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=badsum"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid

хотя я его и не трогал после установки.

Спасибо!

**Comment by Anonym-tsk** [comment]
Пожалуйста, переустановите скрипты. У вас довольно старая верси

**Comment by bor2121** [comment]
Переставил удалённо. Домашние сказали работает! Спасибо!
