### ISSUE TITLE
Бесконечная загрузка видео на декстопе, мобильных устройствах, телевизорах (Tizen)

### ISSUE THREAD

**Issue by perosnamjl** [Anonym-tsk/nfqws-keenetic#2]
**Опишите проблему**
Подробно опишите что делали и что не работает.
Бесконечная загрузка видео на декстопе, мобильных устройствах, телевизорах (Tizen). Сама страница YouTube открывает, но видео бесконечно грузит. Модули  "Протокол IPv6" и "Модули ядра подсистемы Netfilter" - установлены. Пробовали также запретить весь UDP трафик на 443 порт для отключения QUIC - не помогло. Провайдер - Билайн. Город - Краснодар.
**Модель маршрутизатора**
Укажите полную модель роутера и прошивку
Keenetic Giga (KN-1011), Версия ОС
4.1.7
**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
> # Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="et3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=badsum"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid

```

`ps | grep nfqws`
```
>  # ps | grep nfqws
 1058 21474836   480 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/op
 1217 root      5400 S    grep nfqws

```

`iptables-save | grep 200`
```
> -A POSTROUTING -o et3 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o et3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass

```

**Comment by Anonym-tsk** [comment]
У вас в конфиге `ISP_INTERFACE="et3"`, а должно быть `ISP_INTERFACE="eth3"`

**Comment by Anonym-tsk** [comment]
Остановите сервис, исправьте конфиг и запустите заново

**Comment by perosnamjl** [comment]
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="eth3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=badsum"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid

**Comment by Anonym-tsk** [comment]
Попробуйте перезагрузить роутер. Возможно эффект от того, что были неверные правила прописаны.

**Comment by perosnamjl** [comment]
Без изменений, в видео бесконечный кружок загрузки.

**Comment by Anonym-tsk** [comment]
Ну можно попробовать с аргументами поиграть.
Открываете конфиг, строчку с аргументами приводите к виду
```
--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4
```
Может поможет.

**Comment by dcttly** [comment]
У меня тоже ни в какую не работал ютуб на лыже-тв, пока в настройках подключения к интернету на роутере не отключил получение от провайдера IPv6. Об этом, кстати, в треде про tpws тоже кто-то упоминал - наверное, можно в инструкции по установке упомянуть.

**Comment by dcttly** [comment]
> ```
> --dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=badsum --dpi-desync-repeats=6 --dpi-desync-any-protocol --dpi-desync-cutoff=d4
> ```
А корректно ли использовать одновременно fake, disorder2 и fooling?  В мануале к zapret написано: 
"Режим disorder2 отключает отправку поддельных частей"
"disorder2 и split2 не предполагают отсылку фейк пакетов, поэтому опции ttl и fooling неактуальны"

**Comment by Anonym-tsk** [comment]
Не могу сказать. На Хабре предлагали такой набор параметров как рабочий. У меня конкретно с этими параметрами не заработало автоматическое добавление доменов

**Comment by eecscorpion** [comment]
> У меня тоже ни в какую не работал ютуб на лыже-тв, пока в настройках подключения к интернету на роутере не отключил получение от провайдера IPv6. Об этом, кстати, в треде про tpws тоже кто-то упоминал - наверное, можно в инструкции по установке упомянуть.

Спасибо, отключение IPv6 помогло на всех устройствах. Интересно для IPv6 возможно настроить?

**Comment by ops244** [comment]
привет ребят, благодарю за скрипт, вопрос, а инста у всех работает с этими настройками? вроде проверил кучу сайтов, работают все, кроме инсты почему-то...

**Comment by ReMicroN** [comment]
> привет ребят, благодарю за скрипт, вопрос, а инста у всех работает с этими настройками? вроде проверил кучу сайтов, работают все, кроме инсты почему-то...

У инсты залочены айпишники, этими способами блокировку не преодолеть, только через ВПН другой страны.

**Comment by Anonym-tsk** [comment]
> только через ВПН другой страны.

Это зависит от провайдера. На каких-то обходится с помощью nfqws

**Comment by eecscorpion** [comment]
> привет ребят, благодарю за скрипт, вопрос, а инста у всех работает с этими настройками? вроде проверил кучу сайтов, работают все, кроме инсты почему-то...

У меня ещё AntiZapret настроен, поэтому работает всё.

**Comment by ops244** [comment]
> > привет ребят, благодарю за скрипт, вопрос, а инста у всех работает с этими настройками? вроде проверил кучу сайтов, работают все, кроме инсты почему-то...
> 
> У меня ещё AntiZapret настроен, поэтому работает всё.

а как они совместно могут работать, если там надо 3 раза чтобы в течении минуты сайт залочен был, чтобы в список попасть? онже просто антизапретом обойдется и всписки не попадет

**Comment by eecscorpion** [comment]
> > > привет ребят, благодарю за скрипт, вопрос, а инста у всех работает с этими настройками? вроде проверил кучу сайтов, работают все, кроме инсты почему-то...
> > 
> > 
> > У меня ещё AntiZapret настроен, поэтому работает всё.
> 
> а как они совместно могут работать, если там надо 3 раза чтобы в течении минуты сайт залочен был, чтобы в список попасть? он-же просто антизапретом обойдется и в списки не попадет

Что не проходит через антизапрет, попадает в список. Всё в порядке же.

**Comment by Anonym-tsk** [comment]
@perosnamjl прошу подтвердить, решена ли проблема

**Comment by perosnamjl** [comment]
Проблема все ещё остается. Не грузит совсем.

**Comment by Anonym-tsk** [comment]
Давайте подробнее.
1. Не грузит конкретные сайты или вообще все?
2. IPv6 отключили?
3. Покажите актуальный конфиг

**Comment by perosnamjl** [comment]
Опишу ситуацию по обходам в общем. 

- Если использовать nfqws: сайт YouTube грузится очень медленно, но кое-как прогружает страницу, если перейти на видео оно в принципе не загружается. Ни на одном устройстве. Отключение IPv6 делал так: Кабель Ethernet - Параметры IP и DNS - Настройка IPv6 - Не используется. После смены этих параметров ложится инет. Но после перезагрузки роутеры сайты грузятся. С YouTube остается та же проблема, что и писал выше.

- Если использовать tpws: тут смотря какие параметры. Если использовать автоматическую установку (с параметрами по умолчанию, что ставится скриптом), то на телевизоре кое-как прогружается сайт (интерфейс все еще медленно), на мобильных устройствах тоже все грузит, но на декстопе сайт кое-как грузится, но не воспроизводит видео. Если из  exclude.list убрать youtube.com, youtu.be и переместить в user.list, то на декстопе все начинает работать, на мобильных устроствах тоже, но на телевизоре (Tizen) не работает. Ошибка сети.

**Comment by Anonym-tsk** [comment]
Я внес некоторые изменения в скрипты.
Попробуйте переустановить nfqws, выберите режим list. При установке согласитесь на перезапить листов.
После переустановки лучше перезагрузить роутер.
Сообщите о результатах.

**Comment by perosnamjl** [comment]
Переустановил, выбрал режим list, отключил ipv6 в веб-интерфейсе кинетика, перезагрузил роутер. Сайт ютуб открывается, но интерфейс прогружает еще секунд 10, при открытии видео - черный экран, и бесконечная загрузка, аналогично на мобильных устройствах - приложение и интерфейс прогружается, но ни одно видео не запускается. На телевизоре сначала серый экран, потом секунд 10 прогружается интерфейс, при запуске видео крутится кружок и потом тупо черный экран. Интерфейс плеера отображает только полоску воспроизведения.

**Comment by jAba65** [comment]
Всем добрый день! есть похожая проблема, на пк и телефонах работает идиально (ютуб и заблокированные сайты) 
На телевизоре же, показывает лого ютуб за тем полностью серый экран 

`# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="ppp0"`

`# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"`

`NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid`

также попробовал режим авто, что бы добавил самостятельно, вроде что то добавил но все ровно не помогло

**Comment by Anonym-tsk** [comment]
А можете в браузере нажать F12, перейти на вкладку Network и там посмотреть куда идут запросы когда вы на ютубе пытаетесь видео смотреть. И какой протокол используется (h2 или h3)

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/cbf25cd4-7327-49a9-8abd-3988588e2132)

**Comment by Anonym-tsk** [comment]
Там сверху на любое поле (Status, Type, Name) нажмите правой кнопкой и поставьте галочку на Protocol

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/8a55e851-4807-4719-bf30-beaece02953c)

**Comment by Anonym-tsk** [comment]
На красных запросах, в частности на videoplayback какой протокол?

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/201549fc-74f0-4152-9f41-136e75f5ae7b)

**Comment by Anonym-tsk** [comment]
Проверяйте что за DNS используется.
Отключите провайдерский DNS, настройте DoH/DoT, проверьте что по DHCP клиентам приходит адрес роутера, а не какой-то другой DNS.

**Comment by Anonym-tsk** [comment]
> Есть инструкция как провайдерский DNS отключить?

В веб-интерфейсе, где настройки провайдера, есть галочка "Не использовать DNS провайдера"

> в настройках DoH/DoT можно прописать днс Яндекса, например?

Можно, есть [инструкция](https://help.keenetic.com/hc/ru/articles/360007687159)

> проверьте что по DHCP клиентам приходит адрес роутера

Основная сеть - Параметры IP - Настройки DHCP - DNS1 вписать ваш локальный адрес роутера (например 192.168.0.1)

**Comment by perosnamjl** [comment]
Игнорировать DNS стоит, прописал локальный адрес роутера, добавил адреса DoH/DoT Яндекса, перезагрузил роутер. Без изменений, на декстопе загружает страницу ютуба, но видео не воспроизводит. На остальных устройствах аналогично.

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/f824ee32-1e13-4b30-840e-1b129fbfd079)
![image](https://github.com/user-attachments/assets/1c17e0c9-17c1-4739-beed-5cd39a24c1c2)
![image](https://github.com/user-attachments/assets/d25a0a36-b682-4b10-ab60-8fbf95780e9d)
![image](https://github.com/user-attachments/assets/32e4703e-ee86-4685-9c31-e09690bf667f)

**Comment by Anonym-tsk** [comment]
На десктопе точно DNS роутера используется?
Отключите десктоп от сети и подключите снова.
Попробуйте в хроме с включенным и выключенным флагом chrome://flags/#enable-quic

**Comment by perosnamjl** [comment]
Точно, отключал и не помогло. Флаг тоже дергал.
Сейчас попробовал tpws переустановить, заработало везде, в том числе на Tizen без необходимости исключать адреса ютуба, но интерфейс также медленно прогружается, но это видимо нормально? Именно на телеках.

**Comment by Anonym-tsk** [comment]
Пока решения для tpws не найдено. Играет, но интерфейс тормозит.

**Comment by eecscorpion** [comment]
> Точно, отключал и не помогло. Флаг тоже дергал. Сейчас попробовал tpws переустановить, заработало везде, в том числе на Tizen без необходимости исключать адреса ютуба, но интерфейс также медленно прогружается, но это видимо нормально? Именно на телеках.

![Screenshot_20240812-164421](https://github.com/user-attachments/assets/9790f74a-5a9d-406b-bd8f-a5062afe54d6)
А этот компонент opkg установлен?

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/aa861896-1d78-456b-a447-d12bae297b34)
да

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/13682a55-f725-43d1-84e7-7f6f368228f1)
на декстопе стоит так

**Comment by Anonym-tsk** [comment]
> на декстопе стоит так

А если вырубить QUIC что-то меняется?

**Comment by perosnamjl** [comment]
> > на декстопе стоит так
> 
> А если вырубить QUIC что-то меняется?

на tpws если enabled нет задержки в 10 секунд перед запуском видео, в disabled есть задержка. При том, что в кинетике у меня прописано правило : 

> Можно попробовать заблокировать QUIC вообще
> 
> Создаём в веб-интерфейсе роутера правило файерволла, блокирующее протокол QUIC:
> Межсетевой экран → Домашняя сеть → Добавить правило
> Включить правило: Включено
> Описание: Блокировать QUIC
> Действие: Запретить
> Протокол: UDP
> Номер порта назначения: Равен 443
> Остальные параметры оставляем без изменений

Не уверен, что стоит и в роутере это правило указывать и в браузере ставить флаг

**Comment by perosnamjl** [comment]
Сейчас ради эксперимента отключил правило в кинетике и видосы запускаются моментально (на декстопе) и на моб.устройствах

**Comment by Anonym-tsk** [comment]
Внёс кое-какие изменения в nfqws, попробуйте переустановить

**Comment by perosnamjl** [comment]
Не помогло к сожалению, секунд 20-30 открывается страница ютуба, при запуске видео бесконечная загрузка, либо черный экран. tpws пока работает

**Comment by Anonym-tsk** [comment]
Запретите провайдерский DNS, настройте DoH/DoT, отключите IPv6 на интерфейсе провайдера на роутере.

**Comment by warez4me** [comment]
Имею tv Samsung(Tizen), Android TV, телефоны Redmi 9, Pova 6 Neo.
Keenetic Giga 1010.
Ростелеком, PPPoE .
Относительно Ютуб.
Поначалу работал tpws , без особой возни с IPv6, DNS и QUIC.
Дня 2 назад телевизоры ушли в отказ, телефоны продолжали работать.
Поставил nfqws - в исходной версии не заработало.
Новый вариант с md5sum, отключенным ipv6 и настроенным DoT - все заработало.
QUIC не трогал.

**Comment by Anonym-tsk** [comment]
> Кстати, ручная установка выдает ошибку
> git: 'remote-htps' is not a git command. See 'git --help'.
> The most similar command is
> remote-https

Кажется, не установили пакет git-http
Рад, что у вас в итоге все заработало

**Comment by perosnamjl** [comment]
> Имею tv Samsung(Tizen), Android TV, телефоны Redmi 9, Pova 6 Neo. Keenetic Giga 1010. Ростелеком, PPPoE . Относительно Ютуб. Поначалу работал tpws , без особой возни с IPv6, DNS и QUIC. Дня 2 назад телевизоры ушли в отказ, телефоны продолжали работать. Поставил nfqws - в исходной версии не заработало. Новый вариант с md5sum, отключенным ipv6 и настроенным DoT - все заработало. QUIC не трогал.
> 
> Кстати, ручная установка выдает ошибку git: 'remote-htps' is not a git command. See 'git --help'. The most similar command is remote-https

Можно подробнее про вариант новый?

**Comment by warez4me** [comment]
> > Кстати, ручная установка выдает ошибку
> > git: 'remote-htps' is not a git command. See 'git --help'.
> > The most similar command is
> > remote-https
> 
> Кажется, не установили пакет git-http Рад, что у вас в итоге все заработало

tpws ставил клоном из первоисточника по хабру.
htps вроде нет такой аббревиатуры..

**Comment by warez4me** [comment]
[perosnamjl]
> 
> Можно подробнее про вариант новый?
Новый, он же текущий :)
Первый вариант в аргументах nfqws имел
--dpi-desync-fooling=badsum
а текущий
--dpi-desync-fooling=md5sig

**Comment by perosnamjl** [comment]
> [perosnamjl]
> 
> > Можно подробнее про вариант новый?
> > Новый, он же текущий :)
> > Первый вариант в аргументах nfqws имел
> > --dpi-desync-fooling=badsum
> > а текущий
> > --dpi-desync-fooling=md5sig

а что вы в DoT прописали? Яндекс?

**Comment by warez4me** [comment]
> 
> а что вы в DoT прописали? Яндекс?

![image_2024-08-13_123116239](https://github.com/user-attachments/assets/d19b5529-4da1-412f-8edc-daad445ded55)

**Comment by Anonym-tsk** [comment]
Давайте вернемся к началу.
Удалите tpws и nfqws.
Перезагрузите роутер.
Убедитесь что пакеты IPv6 и Netfilter установлены.
Установите nfqws.
Покажите вывод команд:
`cat /opt/etc/nfqws/nfqws.conf`
`ps | grep nfqws`
`iptables-save | grep 200`
`ip addr show`

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/5bcea59c-61a7-4cc3-b002-32cdf7dfc801)
![image](https://github.com/user-attachments/assets/80661e6d-ba4d-4950-8945-13e25d37cb2d)
![image](https://github.com/user-attachments/assets/55898209-6d8e-4032-a27e-309a14f9caeb)
![image](https://github.com/user-attachments/assets/afa5cfcb-483a-45e4-94f9-d7d3034b1b84)

Удалил, перезагрузил роутер, проверил компоненты, установил nfqws, указал mipsel, eth3 и auto, вывод команд ниже

`# cat /opt/etc/nfqws/nfqws.conf`
```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="eth3"

-sh: /opt/root: Permission denied
# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"
~ # # Provider network interface, e.g. eth3
~ # # You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE
="eth3 nwg1"
~ # ISP_INTERFACE="eth3"
~ #
~ # # All arguments here: https://github.com/bol-van/zapret (search for `nfqws`
on the page)
~ # NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desyn
c-ttl=6 --dpi-desync-fooling=md5sig"
~ # NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/e
tc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclu
de=/opt/etc/nfqws/exclude.list"
~ #
~ # NFQUEUE_NUM=200
~ # PIDFILE=/opt/var/run/nfqws.pid
~ # ~ # cat /opt/etc/nfqws/nfqws.conf
-sh: /opt/root: Permission denied
~ # # Provider network interface, e.g. eth3
~ # # You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE
="eth3 nwg1"

```

`# ps | grep nfqws`

```
 1580 21474836   480 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/op
 2103 root      5400 S    grep nfqws
```
`iptables-save | grep 200`

```
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
```

`ip addr show`


```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
3: sit0@NONE: <NOARP> mtu 1480 qdisc noop qlen 1
    link/sit 0.0.0.0 brd 0.0.0.0
4: gre0@NONE: <NOARP> mtu 1476 qdisc noop qlen 1
    link/gre 0.0.0.0 brd 0.0.0.0
5: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
6: ethoip0@NONE: <BROADCAST,MULTICAST> mtu 1458 qdisc noop qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
7: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop qlen 1
    link/tunnel6 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00 brd 00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
8: ezcfg0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether ea:65:82:d3:c6:0a brd ff:ff:ff:ff:ff:ff
    inet 78.47.125.180/32 brd 78.255.255.255 scope global ezcfg0
       valid_lft forever preferred_lft forever
9: eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq qlen 2000
    link/ether 50:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:fead:1ce8/64 scope link
       valid_lft forever preferred_lft forever
10: eth3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br3 qlen 2000
    link/ether 50:ff:20:ad:1c:e9 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:fead:1ce9/64 scope link
       valid_lft forever preferred_lft forever
11: ra0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 qlen 1000
    link/ether 50:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:fead:1ce8/64 scope link
       valid_lft forever preferred_lft forever
12: ra1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master br1 qlen 1000
    link/ether 52:ff:20:1d:1c:e8 brd ff:ff:ff:ff:ff:ff
13: ra2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:2d:1c:e8 brd ff:ff:ff:ff:ff:ff
14: ra3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:3d:1c:e8 brd ff:ff:ff:ff:ff:ff
15: ra4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:4d:1c:e8 brd ff:ff:ff:ff:ff:ff
16: ra5: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:5d:1c:e8 brd ff:ff:ff:ff:ff:ff
17: ra6: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:6d:1c:e8 brd ff:ff:ff:ff:ff:ff
18: ra7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether 52:ff:20:7d:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7d:1ce8/64 scope link
       valid_lft forever preferred_lft forever
19: ra8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 qlen 1000
    link/ether 52:ff:20:8d:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe8d:1ce8/64 scope link
       valid_lft forever preferred_lft forever
20: ra9: <BROADCAST,MULTICAST> mtu 1500 qdisc noop master br1 qlen 1000
    link/ether 52:ff:20:9d:1c:e8 brd ff:ff:ff:ff:ff:ff
21: ra10: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
22: ra11: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:bd:1c:e8 brd ff:ff:ff:ff:ff:ff
23: ra12: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:cd:1c:e8 brd ff:ff:ff:ff:ff:ff
24: ra13: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:dd:1c:e8 brd ff:ff:ff:ff:ff:ff
25: ra14: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 52:ff:20:ed:1c:e8 brd ff:ff:ff:ff:ff:ff
26: ra15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel qlen 1000
    link/ether 52:ff:20:fd:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefd:1ce8/64 scope link
       valid_lft forever preferred_lft forever
27: apcli0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 56:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
28: apcli1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop qlen 1000
    link/ether 5a:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
29: eth2.1@eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0
    link/ether 50:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:fead:1ce8/64 scope link
       valid_lft forever preferred_lft forever
30: eth2.2@eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1
    link/ether 52:ff:20:ad:1c:e7 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fead:1ce7/64 scope link
       valid_lft forever preferred_lft forever
31: eth2.4@eth2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br3
    link/ether 50:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::52ff:20ff:fead:1ce8/64 scope link
       valid_lft forever preferred_lft forever
32: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 50:ff:20:ad:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fde1:37ba:98:0:52ff:20ff:fead:1ce8/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::52ff:20ff:fead:1ce8/64 scope link
       valid_lft forever preferred_lft forever
33: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 52:ff:20:ad:1c:e7 brd ff:ff:ff:ff:ff:ff
    inet 10.1.30.1/24 brd 10.1.30.255 scope global br1
       valid_lft forever preferred_lft forever
    inet6 fe80::50ff:20ff:fead:1ce7/64 scope link
       valid_lft forever preferred_lft forever
34: br3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue
    link/ether 50:ff:20:ad:1c:e9 brd ff:ff:ff:ff:ff:ff
    inet 100.126.220.165/16 brd 100.126.255.255 scope global br3
       valid_lft forever preferred_lft forever
    inet6 fe80::52ff:20ff:fead:1ce9/64 scope link
       valid_lft forever preferred_lft forever
35: ra7.1@ra7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 qlen 1000
    link/ether 52:ff:20:7d:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7d:1ce8/64 scope link
       valid_lft forever preferred_lft forever
36: ra15.1@ra15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 qlen 1000
    link/ether 52:ff:20:fd:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefd:1ce8/64 scope link
       valid_lft forever preferred_lft forever
37: ra7.2@ra7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 qlen 1000
    link/ether 52:ff:20:7d:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fe7d:1ce8/64 scope link
       valid_lft forever preferred_lft forever
38: ra15.2@ra15: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 qlen 1000
    link/ether 52:ff:20:fd:1c:e8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::50ff:20ff:fefd:1ce8/64 scope link
       valid_lft forever preferred_lft forever

```

**Comment by perosnamjl** [comment]
На декстопе заработало и грузит моментально, на моб устройствах и Tizen не грузит, серый экран

**Comment by Anonym-tsk** [comment]
А покажите еще вкладку "Контентный фильтр". Не используется ли там случайно какой-нибудь NextDNS?

**Comment by Anonym-tsk** [comment]
Ну у вас интернет точно не на eth3. Покажите какой айпишник в веб-интерфейсе роутера от провайдера

**Comment by perosnamjl** [comment]
![image](https://github.com/user-attachments/assets/8bf16903-3a85-41d1-b4b2-e6fcfc66a0fa)
![image](https://github.com/user-attachments/assets/6e6b7005-b4fb-4bc8-8f6d-89886946a30d)

**Comment by Anonym-tsk** [comment]
Ваш интерфейс br3. Перенастройте nfqws и проверьте. Должно заработать.

**Comment by perosnamjl** [comment]
в хроме Kyber и QUIC отключить?

**Comment by Anonym-tsk** [comment]
Да можно не отключать ничего пока, должно заработать так

**Comment by perosnamjl** [comment]
Заработало везде, но на Tizen есть конечно тормоза. Но намного лучше чем twps. Спасибо вам за терпение и труды!

**Comment by Anonym-tsk** [comment]
Рад, что всё сложилось.
Можете поиграть с параметрами nfqws, если есть понимание. Возможно, найдете подходящие для вашего ТВ.
