### ISSUE TITLE
[BUG] Не работает YouTube на mi tv stick 4k

### ISSUE THREAD

**Issue by PlatiniX** [Anonym-tsk/nfqws-keenetic#27]
Не работает YouTube на mi tv stick 4k, пишет что нет подключения к сети. Как только останавливаешь nfqws, то YouTube включается сразу же. На ноутбуках, планшете и телефонах проблем нет.

Роутер SmartBox Giga перешитый в Keenetic Giga.

Мобильный интернет Yota через модем Huawei E3272 , интерфейс cdc_br0

`/opt/etc/init.d/S51nfqws version`
```
nfqws-keenetic version: 1.2.0

```

`/opt/etc/init.d/S51nfqws restart`
```
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
Stopping NFQWS service...
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/user.list
Started NFQWS service

```

`cat /opt/etc/nfqws/nfqws.conf`
```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="cdc_br0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Try different variants
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badseq"
#NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=12 --dpi-desync-fooling=badseq"
#NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badsum"
#NFQWS_ARGS="--dpi-desync=fake,split2 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig"
#NFQWS_ARGS="--dpi-desync=fake,split --dpi-desync-ttl=7 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

NFQUEUE_NUM=200
IPV6_ENABLED=0
HTTP_ENABLED=0
PIDFILE=/opt/var/run/nfqws.pid

# Syslog logging level (0 - silent, 1 - debug)
LOG_LEVEL=0

```

`ps | grep nfqws`
```
28300 nobody     556 S    /opt/usr/bin/nfqws --daemon --user=nobody --qnum=200 --pidfile=/opt/var/run/nfqws
28351 root      5400 S    grep nfqws

```

`iptables-save | grep 200`
```
-A POSTROUTING -o cdc_br0 -p tcp -m tcp --dport 80 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A _NDM_IP_PROTECT -p tcp -m tcp --dport 8200 -j _NDM_SL_PROTECT

```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0

```

**Comment by vodyanov** [comment]
Похоже больше не работает. У меня Keenetic Viva, пару дней назад еще более менее работал tpws-keenetic, но всё хуже и хуже. Сейчас уже и он не работает и nfqws-keenetic. Все рекомендации пробовал. 
`~ # curl --connect-to ::speedtest.selectel.ru https://manifest.googlevideo.com/100MB -k -o/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:39 --:--:--     0
curl: (52) Empty reply from server` 

Причем чрез сотовую сеть пакеты идут.

`a111@MacBook-Pro-111 ~ % curl --connect-to ::speedtest.selectel.ru https://googlevideo.com/100MB -k -o/dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 73  100M   73 73.2M    0     0  3787k      0  0:00:27  0:00:19  0:00:08 2459k`

Скриншет работы через nfqws-keenetic
<img width="1392" alt="Снимок экрана 2024-08-30 в 12 40 27" src="https://github.com/user-attachments/assets/2d936069-773b-43d2-8ae7-edd632635d2d">

Сейчас на ГитХабе нашел альтернативное решение, буду пробовать.

**Comment by Anonym-tsk** [comment]
Не установлен пакет Netfilter
