### ISSUE TITLE
[BUG] Не работают видео в браузере на ПК, в приложении и браузере телефона 

### ISSUE THREAD

**Issue by Figaroo777** [Anonym-tsk/nfqws-keenetic#3]
**Опишите проблему**
Установил программу по инструкции, после этого Youtube заработал на Android TV и на Samsung Tizen. В то же время в браузере на ПК, в приложении и браузере телефона видео не работают. 
До этого пробовал Вашу программу [tpws-keenetic], на ней вообще ничего на работало, тут хотя бы телевизоры запустились, за это большое спасибо, но хотелось бы также иметь возможность использовать Youtube на ПК и телефоне.

**Модель маршрутизатора**
Keenetic Ultra (KN-1811), прошивка 4.1.7

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`
```
> # Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="et                                                                             h3 nwg1"
ISP_INTERFACE="eth3 br0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on t                                                                             he page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-tt                                                                             l=6 --dpi-desync-fooling=badsum"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/n                                                                             fqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/                                                                             opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid

```

`ps | grep nfqws`
```
> 961 21474836   524 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/opt/var/run/nfqws.pid --dpi-desync=fake disorder2 --dpi-desync-split-pos=1 --dp
 1388 root      5976 D    grep nfqws
```

`iptables-save | grep 200`
```
> -A POSTROUTING -o br0 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o br0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass

```

**Comment by Anonym-tsk** [comment]
Зачем вы интерфейс br0 добавили в конфиг?

**Comment by Figaroo777** [comment]
> Зачем вы интерфейс br0 добавили в конфиг?

На всякий случай видимо ) нужно убрать?

**Comment by Anonym-tsk** [comment]
Нужно убрать

**Comment by Anonym-tsk** [comment]
Уточню. Остановить сервис, убрать из конфига, запустить сервис

**Comment by Figaroo777** [comment]
> Уточню. Остановить сервис, убрать из конфига, запустить сервис

С сожалению не понял, как его останавливать и вновь запускать, поэтому запустил команду автоматического удаления, после чего переустановил его только с дефолтным протоколом eth3. Проблема осталась, сам сайт прогружается но видео не стартуют

**Comment by frav1s** [comment]
Кстати, такая же ситуация, только вчера поставил на 1811, все работало. А вот буквально час назад все упало

**Comment by dcttly** [comment]
> > Уточню. Остановить сервис, убрать из конфига, запустить сервис
> 
> С сожалению не понял, как его останавливать и вновь запускать, поэтому запустил команду автоматического удаления, после чего переустановил его только с дефолтным протоколом eth3. Проблема осталась, сам сайт прогружается но видео не стартуют

/opt/etc/init.d/S51nfqws stop
/opt/etc/init.d/S51nfqws start

**Comment by Figaroo777** [comment]
> > > Уточню. Остановить сервис, убрать из конфига, запустить сервис
> > 
> > 
> > С сожалению не понял, как его останавливать и вновь запускать, поэтому запустил команду автоматического удаления, после чего переустановил его только с дефолтным протоколом eth3. Проблема осталась, сам сайт прогружается но видео не стартуют
> 
> /opt/etc/init.d/S51nfqws stop /opt/etc/init.d/S51nfqws start

Cпасибо, попробовал, терминал реагирует, командами перезапустил сервис, но проблема осталась. Кстати, можете пояснить, что такое /opt/?
Папка etc у меня в корне отображается, папки otc соответственно не вижу. Но скрипт запускается все равно

**Comment by SPIRITUFA** [comment]
> /opt/

Грубо говоря это память либо устройство куда накатывается entware.

**Comment by Figaroo777** [comment]
Нашел решение проблемы. На роутере нужно отключить IPV6, тогда youtube начинает работать на всех устройствах. Отключение этого параметра как-то влияет на возможности использования интернета?

![В гит](https://github.com/user-attachments/assets/834dd551-9380-4fcc-bfab-dd4fa8581058)

**Comment by dcttly** [comment]
Да считайте, что никак не влияет. На эту особенность работы уже много где указывали, я где-то предлагал автору в руководстве указать необходимость отключения IPv6, чтобы все работало. Ну либо дополнить код правилами для ipv6,

**Comment by Anonym-tsk** [comment]
Правила для IPv6 в процессе

**Comment by frav1s** [comment]
Спасибо, отключение ipv6 помогло!!

**Comment by perosnamjl** [comment]
> Нашел решение проблемы. На роутере нужно отключить IPV6, тогда youtube начинает работать на всех устройствах. Отключение этого параметра как-то влияет на возможности использования интернета?
> 
> ![В гит](https://private-user-images.githubusercontent.com/178075989/356871535-834dd551-9380-4fcc-bfab-dd4fa8581058.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTE5MjIsIm5iZiI6MTcyMzM5MTYyMiwicGF0aCI6Ii8xNzgwNzU5ODkvMzU2ODcxNTM1LTgzNGRkNTUxLTkzODAtNGZjYy1iZmFiLWRkNGZhODU4MTA1OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNTUzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjhiYWRhMjc4N2ZhOGE0ZTEwMzYzM2NiNDIzYjhiYzlkYTA5ZTBiMzQ2MDdlNDliNTBhNzVmMmY0NWIyNWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vre6gV5ZTJMgnTBEaanfdqyJDOavcFqZ5NsuL7BHu_Y)

лично у меня после отключения отвалился инет(

**Comment by eecscorpion** [comment]
> Правила для IPv6 в процессе

Продублировал в S51nfqws 45, 46 и 62, 63 строку, iptables заменил на ip6tables, т.к. автор пишет что  ip6tables работает для nfqws также как и iptables. Работает с включённым IPv6.

**Comment by Anonym-tsk** [comment]
Добавлена поддержка IPv6, можно проверять.

**Comment by Figaroo777** [comment]
> Добавлена поддержка IPv6, можно проверять.

Нужно все переустановить или просто что-то заменить?

**Comment by Anonym-tsk** [comment]
> Нужно все переустановить или просто что-то заменить?

Просто переустановите

**Comment by Figaroo777** [comment]
> Добавлена поддержка IPv6, можно проверять.

Переустановил, пока все работает. Большое спасибо за труд!
