### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by fakir81** [Anonym-tsk/nfqws-keenetic#47]
**Подробно опишите проблему**
Роутер Asus RT-N56U, OpenWRT 23.05.4 перенесена на usb, архитектура mipsel. 
На команду uname -m, ответ mips. Соответственно и устанавливается бинарник mips, который не запускается.
**Какое решение вы предлагаете?**
Сделать разделение репозиториев как на Keenetic или что то подобное, чтобы можно было явно указать для какой архитектуры  бинарник устанавливать.
...

**Comment by fakir81** [comment]
Я изначально тоже пробовал cat /proc/cpuinfo, ответ permission denied, хотя права root

**Comment by Anonym-tsk** [comment]
В следующей версии будет исправлено
