### ISSUE TITLE
[Feature request] Просьба добавить вариант инструкции для прошивки Padavan

### ISSUE THREAD

**Issue by AndreyTG** [Anonym-tsk/nfqws-keenetic#48]
**Подробно опишите проблему**

RM-AC2100_3.4.3.9L-102-d44d448

Устройство Redmi AC2100, прошивка с 4PDA.
...
Просьба добавить вариант инструкции для прошивки Padavan, установка проходит как для кинетика, но в конце сервис не стартует и ругается на невозможность создать Iptables. (Могу предоставить устройство для удаленного теста, дебага, если поможет).

xt_multiport.ko loaded
xt_connbytes.ko loaded
xt_NFQUEUE.ko loaded
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
ip6tables: No chain/target/match by that name.
Started NFQWS service

**Какое решение вы предлагаете?**
Пожалуйста, помогите, что делать?

**Comment by anch665** [comment]
Вам надо пересобрать прошивку с поддержкой NFQUEUE
https://4pda.to/forum/index.php?showtopic=714487&view=findpost&p=132297351

сам много лет просидел на Padavan, но ушел на Keenetic
