### ISSUE TITLE
[Feature request] Поддержка IPv6

### ISSUE THREAD

**Issue by dartraiden** [Anonym-tsk/nfqws-keenetic#5]
Стоит как-то определять, имеется ли на интерфейсе WAN адрес IPv6 и, если имеется, добавлять правила ip6tables. Либо упомянуть в ридми, что IPv6 стоит отключить. Иначе, если приложение лезет по IPv6, трафик не заворачивается на tpws/nfqws.

**Comment by Anonym-tsk** [comment]
https://github.com/Anonym-tsk/nfqws-keenetic/commit/51639120485ade10056c5b2b87bd131a962d7191
