### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by Neytrino-OnLine** [Anonym-tsk/nfqws-keenetic#52]
Нельзя ли вместо/вместе с:
/opt/etc/init.d/S51nfqws {start|stop|restart|reload|status}
добавить команды для вызова этих функций (типа):
nk {start|stop|restart|reload|status}
(как у других приложений)?

**Comment by IronButterfly** [comment]
alias же можно в профиль прописать, как тут, например: https://t.me/nfqws/8466

**Comment by Neytrino-OnLine** [comment]
IronButterfly, спасибо - попробую. Но возможно стоит реализовать это централизованно..?
