### ISSUE TITLE
[BUG] Установка на OpenWRT пункт 2

### ISSUE THREAD

**Issue by pumi** [Anonym-tsk/nfqws-keenetic#54]
**Опишите проблему**

на пункте Установка на OpenWRT
2 Установите публичный ключ репозитория
выполняю команды
wget -O "/tmp/nfqws-keenetic.pub" "https://anonym-tsk.github.io/nfqws-keenetic/openwrt/nfqws-keenetic.pub"
opkg-key add /tmp/nfqws-keenetic.pub
и Получаю opkg-key: not found
![Снимок экрана 2024-09-18 061011](https://github.com/user-attachments/assets/623223e1-68e5-4ec5-baa6-4f90a08d7c60)

**Модель маршрутизатора**
Укажите полную модель роутера и прошивку Hopper SE (KN-3812) EAEU, 4.1.7

**Comment by Anonym-tsk** [comment]
А у вас на Hopper SE точно OpenWRT установлена?

**Comment by pumi** [comment]
Ох извинияюсь, я очень "протупил" похоже, всё делал в 5 часов ночи/утра, плохо соображал. 
 Установка на Keenetic и Entware  всё сделал и пропустив раздел Установка на OpenWRT (это для роутеров на опенврт раздел) просто перехожу в Настройки.
Я из раздела OpenWRT выполнил первые два пункта. Это не помешает? Ещё раз Установка на Keenetic и Entware  выполнять все пункты не надо и сразу Настройки?

**Comment by Anonym-tsk** [comment]
Просто начните установку с начала по нужной инструкции
