### ISSUE TITLE
[BUG] Не запускается

### ISSUE THREAD

**Issue by happyonefriend** [Anonym-tsk/nfqws-keenetic#58]
**Опишите проблему**
Подробно опишите что делали и что не работает.

Установил nfqws, но постоянно пишет что is stopped, не могу запустить, хотя tpws запускался раньше, с ним всё было в порядке
Запускаю скрипт с параметром start - пишет "started", запрашиваю статус - всегда is stopped и ничего не открывает
С tpws таких проблем нет, но tpws работает только на одном компьютере, на других устройствах перестало работать

**Модель маршрутизатора**
Укажите полную модель роутера и прошивку

Keenetic Giga (KN-1010), Entware

**Провайдер**
Укажите вашего провайдера и тип подключения (ppp/ethernet/...)

pppoe, Ростелеком

**Выполните команды и приложите их вывод**
`opkg info nfqws-keenetic`
```
Package: nfqws-keenetic
Version: 2.1.2
Depends: iptables
Status: unknown ok not-installed
Section: net
Architecture: all
Size: 469008
Filename: nfqws-keenetic_2.1.2_all_entware.ipk

Package: nfqws-keenetic
Version: 2.1.2
Depends: iptables
Status: install user installed
Architecture: mipsel-3.4
Conffiles:
 /opt/etc/nfqws/nfqws.conf 7cd5e4e527f4418d42987544b6e7003a83e9face665739c2d967d1a8b6042e16
 /opt/etc/nfqws/user.list 209e09786d508f45a63f72596d728697a9c70c5bbfabd8d3fc1bf267307d4084
 /opt/etc/nfqws/auto.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/exclude.list 57b5e33196908b3b76004679bb800bcf2eb5a41ee82e4d5048c6fd32a0524834
Installed-Time: 1726812663

```

`/opt/etc/init.d/S51nfqws restart`
```
Service NFQWS is not running
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 1 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 38 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 1 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 38 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Started NFQWS service

```

`cat /opt/etc/nfqws/nfqws.conf`
```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="ppp0"
ISP_INTERFACE="ppp0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Try different variants
#NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badseq,badsum"
#NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=12 --dpi-desync-fooling=badseq"
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badsum"
#NFQWS_ARGS="--dpi-desync=fake,split2 --dpi-desync-ttl=0 --dpi-desync-fooling=md5sig"
#NFQWS_ARGS="--dpi-desync=fake,split --dpi-desync-ttl=7 --dpi-desync-fooling=md5sig"

NFQWS_ARGS_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-cutoff=d4 --dpi-desync-fooling=badsum"

# auto - automatically detects blocked resources and adds them to the auto.list
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

# list - applies rules only to domains in the user.list
#NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

# all  - applies rules to all traffic except domains from exclude.list
#NFQWS_EXTRA_ARGS="--hostlist-exclude=/opt/etc/nfqws/exclude.list"

# IPv6 support
IPV6_ENABLED=0

# HTTP support
HTTP_ENABLED=0

# QUIC support
QUIC_ENABLED=1

# Syslog logging level (0 - silent, 1 - debug)
LOG_LEVEL=0

NFQUEUE_NUM=200
NFQUEUE_NUM_QUIC=210

```

`ps | grep nfqws`
```
 4028 nobody     556 S    /opt/usr/bin/nfqws --daemon --user=nobody --qnum=200
 4094 nobody     588 S    /opt/usr/bin/nfqws --daemon --user=nobody --qnum=210
 8045 root      5400 S    grep nfqws
```

`iptables-save | grep 200`
```
-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A @PPPoE0 -s 93.153.200.118/32 -p tcp -j ACCEPT
-A _NDM_IP_PROTECT -p tcp -m tcp --dport 8200 -j _NDM_SL_PROTECT

```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by Neytrino-OnLine** [comment]
На работающем экземпляре, в "opkg info nfqws-keenetic":
Status: install user installed (у вас: unknown ok not-installed)
Попробуйте удалить, и ещё раз внимательно пройти по инструкции (возможно вы не поставили что-то из необходимого)...

**Comment by happyonefriend** [comment]
> На работающем экземпляре, в "opkg info nfqws-keenetic": Status: install user installed (у вас: unknown ok not-installed) Попробуйте удалить, и ещё раз внимательно пройти по инструкции (возможно вы не поставили что-то из необходимого)...

Переустановка результата не дала, сейчас status корректный "install user installed" но проблема на месте
```
Package: nfqws-keenetic
Version: 2.2.1
Depends: iptables, busybox
Status: install user installed
Section: net
Architecture: all
Size: 478281
Filename: nfqws-keenetic_2.2.1_all_entware.ipk
Conffiles:
 /opt/etc/nfqws/nfqws.conf 1d5d2a7f375dfb1cc12eec81dfd067b9ff1bac99b7b6bedb2ce39731af541961
 /opt/etc/nfqws/fake.list 209e09786d508f45a63f72596d728697a9c70c5bbfabd8d3fc1bf267307d4084
 /opt/etc/nfqws/user.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/auto.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/exclude.list 57b5e33196908b3b76004679bb800bcf2eb5a41ee82e4d5048c6fd32a0524834
Installed-Time: 1726831237

```

![Screenshot_1](https://github.com/user-attachments/assets/23b21a89-de5a-4cf2-8752-e0ddc2e17dd7)

**Comment by happyonefriend** [comment]
Проблему решил следующим образом:
1) Удалил скрипт автоматического поиска стратегии
2) Удалил все DoT
3) Удалил полностью тайцы
4) Перезагрузил роутер
5) Прописал в интернет-фильтрах DoT
6) Установил с нуля тайцы
Всё заработало как надо

**Comment by alexxxsubbota** [comment]
> 6\. Установил с нуля тайцы
>     Всё заработало как надо

Я даж вместо обновления каждый раз переустанавливаю. На всякий. На кинетике вообще удобно, можно даж enthware в пару нажатий перустановить. Такой удобной прошивки я еще не втречал у других производителей.

**Comment by Lum1nus** [comment]
> Проблему решил следующим образом:
> 
> 1. Удалил скрипт автоматического поиска стратегии
> 2. Удалил все DoT
> 3. Удалил полностью тайцы
> 4. Перезагрузил роутер
> 5. Прописал в интернет-фильтрах DoT
> 6. Установил с нуля тайцы
>    Всё заработало как надо

что такое тайцы

**Comment by happyonefriend** [comment]
> > Проблему решил следующим образом:
> > 
> > 1. Удалил скрипт автоматического поиска стратегии
> > 2. Удалил все DoT
> > 3. Удалил полностью тайцы
> > 4. Перезагрузил роутер
> > 5. Прописал в интернет-фильтрах DoT
> > 6. Установил с нуля тайцы
> >    Всё заработало как надо
> 
> что такое тайцы

Отредактировал, сорри, Punto Switcher не признал английского nfqws и решил что я пишу про тайцев)
