### ISSUE TITLE
[BUG] Многие домены не добавляются в auto.list

### ISSUE THREAD

**Issue by Gorodskih** [Anonym-tsk/nfqws-keenetic#64]
**Опишите проблему**
Не все сайты автоматически добавляются в auto.list. Например, "x.com" и соответствующие домены определились и добавились.
Однако многие заблокированные домены, вроде "rutracker.org" не определяются автоматически.
При добавлении в user.list сайт сразу же начинает работать на стандартной стратегии.
strategy.sh находил стратегии, но на некоторые из них ругался на сертификат. Например:
```
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
we have 1 user defined desync profile(s) and default low priority profile 0
Found strategy:
--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig
```
Отключил работающий IPv6 на PPoE. Отключил IntelliQoS. Отключил сетевой ускоритель командой "no ppe" в cli (сохранить не забыл).
Теперь strategy.sh --full совсем не находит стратегии. На всё отвечает примерно следущее:
```
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
we have 1 user defined desync profile(s) and default low priority profile 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```
При этом с tpws такой проблемы нет.

**Модель маршрутизатора**
 Ultra (KN-1811) EAEU 4.2.0

**Провайдер**
Дом.ру PPPoE

**Выполните команды и приложите их вывод**
`opkg info nfqws-keenetic`
```
Package: nfqws-keenetic
Version: 2.2.1
Depends: iptables, busybox
Status: install user installed
Section: net
Architecture: aarch64-3.10
Size: 121270
Filename: nfqws-keenetic_2.2.1_aarch64-3.10.ipk
Conffiles:
 /opt/etc/nfqws/nfqws.conf 1d5d2a7f375dfb1cc12eec81dfd067b9ff1bac99b7b6bedb2ce39731af541961
 /opt/etc/nfqws/fake.list 209e09786d508f45a63f72596d728697a9c70c5bbfabd8d3fc1bf267307d4084
 /opt/etc/nfqws/user.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/auto.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/exclude.list 57b5e33196908b3b76004679bb800bcf2eb5a41ee82e4d5048c6fd32a0524834
Installed-Time: 1726966982
```

`/opt/etc/init.d/S51nfqws restart`
```
Stopping NFQWS service...
we have 4 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/etc/nfqws/fake.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/fake.list
Loading hostlist /opt/etc/nfqws/fake.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/fake.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 6 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 6 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Started NFQWS service
```

`cat /opt/etc/nfqws/nfqws.conf`
```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="ppp0"
ISP_INTERFACE="ppp0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# Base strategy
NFQWS_ARGS="--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig,badseq"
NFQWS_ARGS_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-cutoff=d4 --dpi-desync-fooling=badsum"

# Fake list strategy (not using NFQWS_EXTRA_ARGS)
NFQWS_ARGS_FAKE="--dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-fooling=md5sig --hostlist=/opt/etc/nfqws/fake.list --dpi-desync-fake-tls=/opt/etc/nfqws/tls_clienthello.bin"
NFQWS_ARGS_FAKE_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-cutoff=d4 --dpi-desync-fooling=badsum --hostlist=/opt/etc/nfqws/fake.list --dpi-desync-fake-quic=/opt/etc/nfqws/quic_initial.bin"

# auto - automatically detects blocked resources and adds them to the auto.list
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

# list - applies rules only to domains in the user.list
#NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

# all  - applies rules to all traffic except domains from exclude.list
#NFQWS_EXTRA_ARGS="--hostlist-exclude=/opt/etc/nfqws/exclude.list"

# IPv6 support
IPV6_ENABLED=1

# HTTP support
HTTP_ENABLED=0

# QUIC support
QUIC_ENABLED=1

# Syslog logging level (0 - silent, 1 - debug)
LOG_LEVEL=0

NFQUEUE_NUM=200
USER=nobody
CONFIG_VERSION=1
```

`ps | grep nfqws`
```
1443 nobody     636 S    /opt/usr/bin/nfqws --daemon --pidfile=/opt/var/run/nfqws.pid --user=nobody --qnum=200 --filter-tcp=443 --dpi-desync=fake split2 --dpi-desync-autottl=2 -
 1497 root      5972 S    grep nfqws
```

`iptables-save | grep 200`
```
-A POSTROUTING -o ppp0 -p udp -m udp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by VladimirMrzv** [comment]
у нас похоже общая проблема
https://github.com/Anonym-tsk/nfqws-keenetic/issues/62

у меня работает только базовая стратегия, fake не отрабатывает.

**Comment by walkman2021** [comment]
KN-1811 2.2.1  Хотел было уже написать что есть какая то проблема в этом духе на примере сайта fost.club
На предыдущих версиях работало на автоматике и прекрасно.  но например рутрекер открывается и я его не добавлял после переустановки.  
Возможно что бы что то сказать определенно надо проводить эксперимент на чистую установку. 
Проблема за хвост не поймана.

**Comment by AndroVGG** [comment]
> у нас похоже одинаковая проблема #62
> 
> у меня работает только базовая стратегия, fake не отрабатывает. Сайты начинают работать после добавления в пользовательский список.

Стратегии fake отрабатывают домены из списка fake.list, в котором по умолчанию домены, связанные с YT.

**Comment by Gorodskih** [comment]
Проверил на Giga (KN-1010) EAEU у другого провайдера. Там такой проблемы нет, сайты добавляются. Но там у провайдера явно какой-то другой тип блокировки, потому что ютуб на андроиде через TPWS даже с "--mss=128" перестал работать.

**Comment by Gorodskih** [comment]
@Anonym-tsk к сожалению, на версии 2.3.2 проблема с Ultra (KN-1811) осталась.

**Comment by Gorodskih** [comment]
Похоже проблема была в AdGuard Home. Не знаю, как провайдер это провернул, но настроенный tls://one.one.one.one:853 возвращает неправильные IP.

**Comment by Gorodskih** [comment]
@Anonym-tsk  Перепроверил всё несколько раз. Но на v2.3.2 проблема, к сожалению, сохраняется.
Заметил, что почему-то сайты открываются с включением "защиты" в Firefox. Посмотрел через Wireshark, а там оказывается включается "Encrypted Client Hello" и в Client Hello в SNI посылается "cloudflare-ech.com" вместо "rutracker.org". А вот без этой самой "защиты" сайты всё равно почему-то не определяются в nfqws как заблокированные.

**Comment by Gorodskih** [comment]
@Anonym-tsk, перепроверил всё несколько раз. Но на v2.3.2 проблема, к сожалению, сохраняется. nfqws всё так же не определяет заблокированный сайт автоматически.
Проверил через Wireshark. Соединение сбрасывается флагом RST в ответе после отправки Client hello, в котором стоит правильный SNI="rutracker.org".

P.S. Заметил, что почему-то сайты открываются и без nfqws с включением "защиты" в Firefox. Посмотрел через Wireshark, а там оказывается включается "Encrypted Client Hello" и в Client Hello в SNI посылается "cloudflare-ech.com" вместо "rutracker.org".
