### ISSUE TITLE
Минимизировать ручную работу по подбору и настройке стратегии обхода

### ISSUE THREAD

**Issue by elxkot** [Anonym-tsk/nfqws-keenetic#66]
**Подробно опишите проблему**
...
Для разных провайдеров требуются разные стратегии обхода, причем в последнее время конкретно на моём провайдере свеже подобранные настройки живут пару дней. Для меня это не особо большая проблема, но регулярно переконфигурировать роутеры семье и знакомым утомляет

**Какое решение вы предлагаете?**
...
По сути в проекте уже есть скрипт strategy.sh, который тестирует разные стратегии и предлагает потенциально рабочие варианты, надо только сделать функцию автоматической записи найденной стратегии в конфиг и периодически запускать скрипт по расписанию. Думаю, это должно существенно уменьшить количество ручных манипуляций

**Comment by Yamaxus** [comment]
Привет. А как правильно пользоваться этим скриптом? Для начала в какую папку копировать? Пробовал в opt\bin\  и usr\bin - выдает ошибку - доступ запрещен
~ # ./strategy.sh www.mos.ru --full
/opt/bin/sh: ./strategy.sh: not found
~ # ./strategy.sh www.mos.ru --full
/opt/bin/sh: ./strategy.sh: not found
~ # strategy.sh www.mos.ru --full
/opt/bin/sh: strategy.sh: Permission denied
~ # cd usr
/usr # bin
/opt/bin/sh: bin: not found
/usr # cd bin
/usr/bin # strategy.sh www.mos.ru --full
/opt/bin/sh: strategy.sh: Permission denied
/usr/bin # strategy.sh
/opt/bin/sh: strategy.sh: Permission denied
/usr/bin #
