### ISSUE TITLE
[BUG] Xiaomi AC2100 Padavan (все необходимые модули установлены).

### ISSUE THREAD

**Issue by AndreyTG** [Anonym-tsk/nfqws-keenetic#67]
**Опишите проблему**
Подробно опишите что делали и что не работает.
 Не стартует сервис, ошибок не выдает. Пожалуйста помогите.

Started NFQWS service
/opt/home/admin # /opt/etc/init.d/S51nfqws status
Service NFQWS is stopped
/opt/home/admin # /opt/etc/init.d/S51nfqws start
we have 4 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/etc/nfqws/fake.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/fake.list
Loading hostlist /opt/etc/nfqws/fake.list
loading plain text list
Loaded 16 hosts from /opt/etc/nfqws/fake.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Started NFQWS service
/opt/home/admin # /opt/etc/init.d/S51nfqws status
Service NFQWS is stopped
/opt/home/admin #
/opt/home/admin # iptables-save | grep "queue-num 200"
-A POSTROUTING -o eth3 -p udp -m udp --dport 443 -m connbytes --connbytes 1:8 -- connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40 000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 -- connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40 000000 -j NFQUEUE --queue-num 200 --queue-bypass
/opt/home/admin #

При попытке старт, рестарт сервиса, выходит сообщение, что сервис начинает стартовать...после этого команда со статусом сообщает, что сервис остановлен.

**Модель маршрутизатора**
Укажите полную модель роутера и прошивку
Xiaomi RM AC2100 

https://4pda.to/forum/index.php?showtopic=975687&st=18200

Прошивка padavan-ng_XIAOMI_RM-AC2100_2024.09.16_13.52.01.zip
**Провайдер**
Укажите вашего провайдера и тип подключения (ppp/ethernet/...)

**Выполните команды и приложите их вывод**
`opkg info nfqws-keenetic`
```
</opt/home/admin # opkg info nfqws-keenetic
Package: nfqws-keenetic
Version: 2.3.2
Depends: iptables, busybox
Conflicts: tpws-keenetic
Status: install user installed
Section: net
Architecture: all
Size: 479934
Filename: nfqws-keenetic_2.3.2_all_entware.ipk
Conffiles:
 /opt/etc/nfqws/nfqws.conf b1d58900fe4b8c5df0bd1535da6ec10fd15f6ea06bf5bdc2b0bd31d7e5861502
 /opt/etc/nfqws/user.list 45dc2adaa172b86d73369c6ed12a8a0e648b851b66293b11514c3b1d4bd3fce6
 /opt/etc/nfqws/auto.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
 /opt/etc/nfqws/exclude.list 57b5e33196908b3b76004679bb800bcf2eb5a41ee82e4d5048c6fd32a0524834
Installed-Time: 1727373487
>
```

`/opt/etc/init.d/S51nfqws restart`
```
</opt/home/admin # /opt/etc/init.d/S51nfqws restart
Service NFQWS is not running
nfnetlink_queue.ko loaded
we have 2 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 15 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/auto.list
loading plain text list
Loaded 0 hosts from /opt/etc/nfqws/auto.list
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 15 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Loading hostlist /opt/etc/nfqws/exclude.list
loading plain text list
Loaded 22 hosts from /opt/etc/nfqws/exclude.list
Started NFQWS service>
```

`cat /opt/etc/nfqws/nfqws.conf`
```
</opt/home/admin # cat /opt/etc/nfqws/nfqws.conf
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3"
ISP_INTERFACE="eth3"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
# HTTP(S) strategy
NFQWS_ARGS="--dpi-desync=fake,split2 --dpi-desync-autottl=2 --dpi-desync-split-pos=1 --dpi-de                                                                sync-fooling=md5sig,badseq --dpi-desync-fake-tls=/opt/etc/nfqws/tls_clienthello.bin"

# QUIC strategy
NFQWS_ARGS_QUIC="--dpi-desync=fake --dpi-desync-repeats=6 --dpi-desync-cutoff=d4 --dpi-desync                                                                -fooling=badsum --dpi-desync-fake-quic=/opt/etc/nfqws/quic_initial.bin"

# auto - automatically detects blocked resources and adds them to the auto.list
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.lis                                                                t --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list                                                                "

# list - applies rules only to domains in the user.list
#NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

# all  - applies rules to all traffic except domains from exclude.list
#NFQWS_EXTRA_ARGS="--hostlist-exclude=/opt/etc/nfqws/exclude.list"

# IPv6 support
IPV6_ENABLED=0

# HTTP support
HTTP_ENABLED=0

# QUIC support
QUIC_ENABLED=1

# Syslog logging level (0 - silent, 1 - debug)
LOG_LEVEL=0

NFQUEUE_NUM=200
USER=nobody
CONFIG_VERSION=2
>
```

`ps | grep nfqws`
```
</opt/home/admin # ps | grep nfqws
 1110 admin     5392 S    grep nfqws
>
```

`iptables-save | grep 200`
```
</opt/home/admin # iptables-save | grep 200
-A POSTROUTING -o eth3 -p udp -m udp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o eth3 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
>
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
</opt/home/admin # sysctl net.netfilter.nf_conntrack_checksum
net.netfilter.nf_conntrack_checksum = 0>
```

Вывод команд, смогу добавить вечером когда буду у роутера...Помогите, пожалуйста.

**Comment by votarum** [comment]
lsmod что показывает?

**Comment by AndreyTG** [comment]
/opt/home/admin # lsmod

ip6table_mangle 992 0 - Live 0x85156000
iptable_mangle 912 1 - Live 0x862fc000
xt_NFQUEUE 1488 2 - Live 0x85f16000
xt_connbytes 1632 2 - Live 0x850e1000
deflate 1344 1 - Live 0x85ec4000
zlib_inflate 12944 1 deflate, Live 0x85ff4000
zlib_deflate 18896 1 deflate, Live 0x85fe8000
lzo 864 1 - Live 0x85ebf000
lzo_compress 2160 1 lzo, Live 0x85f27000
lzo_decompress 1504 1 lzo, Live 0x85f55000
ubifs 157088 1 - Live 0x85000000
crc16 1024 1 ubifs, Live 0x85f6c000
rt_timer_wdg 688 0 - Live 0x85f2e000
hw_nat 17664 0 - Live 0x85eb0000
mt76x3_ap 649008 1 - Live 0x86000000
mt7615_ap 1625392 1 - Live 0x86400000

Добавил все выводы команд.

**Comment by votarum** [comment]
не вижу у вас необходимых модулей
```
nfnetlink_queue
nfnetlink
```

**Comment by AndreyTG** [comment]
modprobe nfnetlink_queue

Вывод после команды отсутствует. 
Спасибо пойду исправлять.

**Comment by votarum** [comment]
> modprobe nfnetlink_queue
> 
> Вывод после команды отсутствует. Спасибо пойду исправлять.

Вывода и не должно быть. Снова lsmod - посмотреть список загруженных модулей. Вы как-то ликбез по линуксу посмотрите, что-ли...

**Comment by votarum** [comment]
есть упех для [goodbyedpi](https://ntc.party/t/%D0%B5%D1%81%D0%BB%D0%B8-%D0%BE%D0%BF%D1%8F%D1%82%D1%8C-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB-%D0%B3%D1%80%D1%83%D0%B7%D0%B8%D1%82%D1%8C%D1%81%D1%8F-youtube-%D0%B8%D0%BB%D0%B8-%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE/10529/336), может быть поможет найти нужные опции для nfqws

**Comment by AndreyTG** [comment]
> > modprobe nfnetlink_queue
> > Вывод после команды отсутствует. Спасибо пойду исправлять.
> 
> Вывода и не должно быть. Снова lsmod - посмотреть список загруженных модулей. Вы какой-то ликбез по линуксу посмотрите, что-ли...

Извиняюсь, в линуксе я полный нуб, себе уже настроил на Кинетике, данный роутер хочу настроить и передать брату, чтобы он не был подвержен блокировкам. Огромное спасибо за помощь и рекомендации в настройке. Буду через час у компа, смогу уточнить появился ли необходимы модуль в статусе активных или нет, если нет попрошу на 4PDA внести корректировку в прошивку и добавить отсутствующие модули.

**Comment by votarum** [comment]
> попрошу на 4PDA внести корректировку в прошивку и добавить отсутствующие модули.

там это уже сделали для вашего роутера

**Comment by votarum** [comment]
> Если можете указать, пост с необходимой версией прошивки, буду весьма признателен.

[пост](https://4pda.to/forum/index.php?showtopic=975687&view=findpost&p=132241943)

**Comment by AndreyTG** [comment]
> > Если можете указать, пост с необходимой версией прошивки, буду весьма признателен.
> 
> [пост](https://4pda.to/forum/index.php?showtopic=975687&view=findpost&p=132241943)

Ставил эту версию до текущей, на ней были ошибки по IPTABLES при старте сервиса.

**Comment by votarum** [comment]
> на ней были ошибки по IPTABLES при старте сервиса.

какого сервиса?

**Comment by AndreyTG** [comment]
> > на ней были ошибки по IPTABLES при старте сервиса.
> 
> какого сервиса?

Сервис 
service nfqws-keenetic 

Ошибка:
iptables: No chain/target/match by that name


После обновления на версию прошивки от Крокодила, эта ошибка ушла.

**Comment by votarum** [comment]
> Ошибка:
> iptables: No chain/target/match by that name

ну а как вы хотели? чтобы оно работало без необходимых модулей?

**Comment by AndreyTG** [comment]
> > Ошибка:
> > iptables: No chain/target/match by that name
> 
> ну а как вы хотели? чтобы оно работало без необходимых модулей?

Я же без претензий, я указал, что на ту версию, на которую Вы выдали линк, в ней проблема с Ipitables).

**Comment by votarum** [comment]
> Я же без претензий, я указал, что на ту версию, на которую Вы выдали линк, в ней проблема с Ipitables).

включили бы модули, не было бы и ошибки

> Модули появились в списке...

и что теперь nfqws?

**Comment by AndreyTG** [comment]
> > Я же без претензий, я указал, что на ту версию, на которую Вы выдали линк, в ней проблема с Ipitables).
> 
> включили бы модули, не было бы и ошибки
> 
> > Модули появились в списке...
> 
> и что теперь nfqws?

Теперь заработало, огромное спасибо. Попробую ребутнуться, будут ли перезапускаться модули после рестарта или нет.

**Comment by AndreyTG** [comment]
> > Я же без претензий, я указал, что на ту версию, на которую Вы выдали линк, в ней проблема с Ipitables).
> 
> включили бы модули, не было бы и ошибки
> 
> > вопрос это будет до первой перезагрузки или нет
> 
> теперь [здесь](https://github.com/Anonym-tsk/nfqws-keenetic/discussions/76) все есть

Спасибо. По инструкции, непонятно следующее:

@Чтобы после перезагрузки nfqws нормально стартовал, в пользовательский скрипт "Выполнить перед инициализацией маршрутизатора" добавляем:

Пользовательский скрипт этот где?) Куда прописывать ), распишите пожалуйста для нубов )

**Comment by votarum** [comment]
> Пользовательский скрипт этот где?) Куда прописывать ), распишите пожалуйста для нубов )

Знаете, это уже не нубство... Сразу строчите вопросы, даже не пытаясь поискать ответ.

**Comment by AndreyTG** [comment]
> > Пользовательский скрипт этот где?) Куда прописывать ), распишите пожалуйста для нубов )
> 
> Знаете, это уже не нубство... Сразу строчите вопросы, даже не пытаясь поискать ответ.

Спасибо всё получилось, низкий поклон, респект и уважуха.
