### ISSUE TITLE
Не воспроизводится видео на телевизоре

### ISSUE THREAD

**Issue by Anonym-tsk** [Anonym-tsk/nfqws-keenetic#7]
Всем добрый день! есть похожая проблема, на пк и телефонах работает идиально (ютуб и заблокированные сайты) 
На телевизоре же, показывает лого ютуб за тем полностью серый экран 

```
# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="ppp0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
```

также попробовал режим авто, что бы добавил самостятельно, вроде что то добавил но все ровно не помогло

_Originally posted by @jAba65 in https://github.com/Anonym-tsk/nfqws-keenetic/issues/2#issuecomment-2283635968_

**Comment by Anonym-tsk** [comment]
@jAba65

**Опишите проблему**
Подробно опишите что делали и что не работает.

**Модель маршрутизатора**
Укажите полную модель роутера и прошивку

**Выполните команды и приложите их вывод**
`cat /opt/etc/nfqws/nfqws.conf`

`ps | grep nfqws`

`iptables-save | grep 200`

Укажите провайдера

**Comment by jAba65** [comment]
Опишите проблему:
Установил по инструкции nfqws
Аргументы подобрал сам `--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6`
ютуб и заблокированные сайти на телефоне и пк работают идиально, на телевизоре же поевляется лого ютуб потом полностью серый экран 

Модель маршрутизатора:
Giga (KN-1011) EAEU
Версия ОС - 4.1.7

Вывод первой комманды: `# Provider network interface, e.g. eth3
# You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="ppp0"

# All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list --hostlist-auto=/opt/etc/nfqws/auto.list --hostlist-auto-debug=/opt/var/log/nfqws.log --hostlist-exclude=/opt/etc/nfqws/exclude.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid`

Вывод второй команды: `4971 21474836 12472 S    /opt/usr/bin/nfqws --daemon --qnum=200 --pidfile=/opt/var/run/nfqws.pid --dpi-desync=disorde
 7177 root      5400 S    grep nfqws`
 
 Вывод третий команды: `-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 80 -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
-A POSTROUTING -o ppp0 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass`

Провайдер - Ростелеком


https://github.com/user-attachments/assets/23221f75-8938-4e76-95e8-084ad37e8ca3

**Comment by Anonym-tsk** [comment]
Попробуйте заблокировать QUIC

Межсетевой экран → Домашняя сеть → Добавить правило
Включить правило: Включено
Описание: Блокировать QUIC
Действие: Запретить
Протокол: UDP
Номер порта назначения: Равен 443
Остальные параметры оставляем без изменений

**Comment by jAba65** [comment]
Сделал, перезагрузил роутер, без изменений

**Comment by Anonym-tsk** [comment]
Покажите `cat /opt/etc/nfqws/user.list`

**Comment by jAba65** [comment]
[user.txt](https://github.com/user-attachments/files/16580932/user.txt)

ваш + взял из goobbyedpi

**Comment by Anonym-tsk** [comment]
А не пробовали оставить только мой?

**Comment by jAba65** [comment]
пробовал только ваш и мод list, ваш и мод авто, этот и авто, этот и лист

**Comment by Anonym-tsk** [comment]
Могу предложить только поиграть с параметрами nfqws.

**Comment by jAba65** [comment]
пробовал, но в них уже я мало толку знаю, не знаю что вписывать что нет, только на рандом, подобрал себе вроде параметры что бы на пк и на телефоне работал, на телевизоре вот не работает

**Comment by jAba65** [comment]
узнал что на телевизоре видемо вообще обход не работает потому что не могу зайти, не на nnm не на rutracker ни на заблокированные сайты

**Comment by jAba65** [comment]
если узнаю как сделать что бы тв рабоатл обязательно напишу сюда

**Comment by Anonym-tsk** [comment]
Тэкс.
Проверяйте что у вас с DNS. По DHCP должен приходить DNS роутера, а на самом роутере лучше прописать DoH/DoT и запретить провайдерский DNS.

**Comment by jAba65** [comment]
Здравствуйте еще раз, протестировал 99999999 вариантов, нашел тот на котором всё работает, без ошибок моментально, теливизор также показывает ютуб 

`Provider network interface, e.g. eth3
You can specify multiple interfaces separated by space, e.g. ISP_INTERFACE="eth3 nwg1"
ISP_INTERFACE="ppp0"

All arguments here: https://github.com/bol-van/zapret (search for `nfqws` on the page)
NFQWS_ARGS="--dpi-desync=fake,disorder2 --dpi-desync-split-pos=1 --dpi-desync-ttl=6 --dpi-desync-fooling=md5sig"
NFQWS_EXTRA_ARGS="--hostlist=/opt/etc/nfqws/user.list"

NFQUEUE_NUM=200
PIDFILE=/opt/var/run/nfqws.pid
`

**Comment by jAba65** [comment]
![image](https://github.com/user-attachments/assets/ad75cb6a-2691-43ac-8440-cd3a9e6a5f9e)
![image](https://github.com/user-attachments/assets/7070bbea-a36d-477c-ae33-ed345b5cfeaa)
поменял dns на гугл (может работать и на других не тестировал)
также тестировал без ipv6 разницы нет

**Comment by jAba65** [comment]
включил игнорировать dns 
в параметрах ip  DNS1 вписал 192.168.1.1

**Comment by Anonym-tsk** [comment]
Проверил у себя. Тоже работает отлично. Добавлю ваш вариант как параметр по умолчанию
