### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ops244** [Anonym-tsk/nfqws-keenetic#70]
**Опишите проблему**
такой вопрос, почему после удаления данного скрипта запрещенные сайты продолжают открываться?

**Модель маршрутизатора**
KN-3812

**Провайдер**
mts

**Выполните команды и приложите их вывод**
`opkg info nfqws-keenetic`
```
<ВСТАВИТЬ СЮДА>
```

`/opt/etc/init.d/S51nfqws restart`
```
<ВСТАВИТЬ СЮДА>
```

`cat /opt/etc/nfqws/nfqws.conf`
```
<ВСТАВИТЬ СЮДА>
```

`ps | grep nfqws`
```
<ВСТАВИТЬ СЮДА>
```

`iptables-save | grep 200`
```
<ВСТАВИТЬ СЮДА>
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
<ВСТАВИТЬ СЮДА>
```

**Comment by ops244** [comment]
если даже полностью удалить entware они будут открываться

**Comment by Anonym-tsk** [comment]
После перезагрузки перестанут. Это особенность работы Netfilter
