### ISSUE TITLE
[Feature request] Тестирование Firefox

### ISSUE THREAD

**Issue by MrIbif** [Anonym-tsk/nfqws-keenetic#71]
**Подробно опишите проблему**
Добрый день. Всё работало ... пока не обновился. СПб, корбина. Точнее как - opkg update , апгрейд и пошел тестировать что-там новенького и вот что получилось:

**Какое решение вы предлагаете?**
Ubuntu 22.04.1 и перестал быть доступен FB, ntc . Вернул фильтр который использовал раньше. Всё равно недоступно. Потом открываю vivaldi  и всё работает как ни в чём не бывало, прям летает. Мысль "или я сошел с ума или...". Удаляю snap firefox, скачиваю архив, запускаю - тоже самое. Перегружаюсь под W11 - ситуация аналогичная. FF не работатет, Vivaldi работает.
Причём в логе даже попыток нет что-то добавить, то есть сначала я вовсе думал что nfqws не заработал, но нет процесс на месте и тестовая команда показывала ветви фильтрации по tcp и udp.
На айфоне в сафаре прекрасно открывалось, а на U11 в вивалди не открывались вышеупомянутые сайты. Всю ночь развлекался и так и эдак , тестировал на другом компе так же по Ub 22.04.1 - поведение одинаковое.

К утру ntc.party через FF уже добавлял правила в логе, но вывалился на заглушку http://blackhole.beeline.ru/  , а Vivaldi , Safari работали как ни в чём не бывало.

К чему опус? вероятно к тому, что работу фильтров стоит проверять на разных браузерах и устройствах. как выясняется не всегда результат одинаковый.

P.S. комп на ночь не выключал и сейчас всё заработало и в FF как ни в чём не бывало. Возможно ночью что-то "крутили" новенькое.

**Comment by Anonym-tsk** [comment]
Разберитесь с используемыми DNS
