### ISSUE TITLE
[BUG] - авто обновление до 2.2.1

### ISSUE THREAD

**Issue by Neytrino-OnLine** [Anonym-tsk/nfqws-keenetic#75]
Опять автоматическое обновление, и опять вы своими настройками затираете мои. За каким!?
Зачем вы несчастный user.list заменяете своим пустым? (в чём сокральный смысл?)

- Давайте сделаем автообновление - настраиваемым.
- Давайте отделим настройки стратегий от остальных настроек (раз вам так принципиально менять их всем)
- Давайте (в случае появления каких-то новых параметров) - научимся добавлять их в существующие файлы конфигурации...

P.S. я несколько дней назад, просил добавить в инструкцию команду - которой можно посмотреть список интерфейсов с IP-шниками (как в старом установщике), вы этот запрос закрыли (вроде как исполненный), но ничего похожего я в инструкции так и не нашёл...

**Comment by Anonym-tsk** [comment]
Давайте по пунктам.

> Давайте сделаем автообновление - настраиваемым.

Вы сами обновляетесь, никакого автообновления не существует. Читайте список изменений перед обновлением. Ваши старые конфиги сохраняются с постфиксом -old

> я несколько дней назад, просил добавить в инструкцию команду - которой можно посмотреть список интерфейсов с IP-шниками

Есть инструкция на все случаи жизни, [вот она](https://www.google.com/search?q=%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C+%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA+%D1%81%D0%B5%D1%82%D0%B5%D0%B2%D1%8B%D1%85+%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%BE%D0%B2+linux)

Ну а вообще, вы можете просто не пользоваться nfqws-keenetic

**Comment by Neytrino-OnLine** [comment]
> Читайте список изменений перед обновлением.
Если вас не затруднит - дайте пожалуйста ссылку, на место - где это можно сделать...

Лично я - процесс обновления не запускал. Возможно это делает entware самостоятельно (лично я (опять-же) никаких изменений в его настройки не вносил, и за остальными приложениями несанкционированных мною обновлений - не замечал).

За ссылку - спасибо, не вижу причин - принципиально не включать её в инструкцию. Сам я линукс не люблю, и на все запросы в гугл (которые смог придумать) ничего внятного не нашёл - по этому и потратил время на создание вопроса...

Пользоваться приложением или нет - я наверное разберусь самостоятельно, но хоть убейте, не понимаю - зачем вы переименовываете файл с автоматически добавленными доменами и доменами пользователя и заменяете их пустыми... Если они уже есть и не пустые - значит это кому-то надо..?

**Comment by Anonym-tsk** [comment]
> но хоть убейте, не понимаю - зачем вы переименовываете файл с автоматически добавленными доменами и доменами пользователя

Потому что с обновлениями менялась структура файлов. Если вы не понимаете, это не значит что все вокруг дураки

**Comment by Neytrino-OnLine** [comment]
И каким образом изменилась структура в файле user.list или auto.list? Как были: "один домен на строку" - так и остались...

Возвращаясь к вопросу про список интерфейсов: я почитал ответы из гугла, и хотел бы таки увидеть команду которую использовали вы... Половина из представленных команд - не работает, вторая половина - выводит тоны лишней информации. У меня нет времени, желания и возможности разбираться с тонкостями и подбором параметров запуска, если я могу просто попросить и получить от вас ту команду - которую вы использовали (если вас не затруднит)...

**Comment by Anonym-tsk** [comment]
> У меня нет времени, желания и возможности разбираться с тонкостями и подбором параметров запуска

У меня нет времени, желания и возможности консультировать каждого по простейшим вопросам.

**Comment by Neytrino-OnLine** [comment]
Ну нет - так нет. Однажды, у кого-то - не будет его для вас... Всего хорошего.
