### ISSUE TITLE
[Feature request] Автообновление

### ISSUE THREAD

**Issue by thenikitadant** [Anonym-tsk/nfqws-keenetic#77]
Привет!

Есть предложение:
А) Автообновление при перезагрузке роутера, перед автозапуском nfqws
Б) Автообновление с проверкой новой версии каждые N времени, если это не создаёт нагрузки

---

Идея пришла после того, как некоторым знакомым я помог установить nfqws, но т.к. они совсем не разбираются в этом, а РКН продолжает что-то ломать, то в дальнейшем приходится мониторить git в ожидании нового обновления, а затем ехать к знакомым или же объяснять им, как обновить версию

**Comment by Riadner** [comment]
Не стоит делать никакого обновления, т.к. в один момент можно испортить вообще всё куче пользователей.

**Comment by Ranger21** [comment]
Может быть сделать опционально и с настройкой в разные дни и только на отстоявшуюся версию какое-то количество дней

**Comment by Anonym-tsk** [comment]
Если нужно автоматическое обновление - используйте cron.

**Comment by thenikitadant** [comment]
> Если нужно автоматическое обновление - используйте cron.

Спасибо за подсказку, не знал о таком)

**Comment by 777Evgeny777** [comment]
На кнопку его поставьте и всех делов
