### ISSUE TITLE
[Feature request] Добавить протокол QUIC

### ISSUE THREAD

**Issue by RDL-28** [Anonym-tsk/nfqws-keenetic#8]
Приветствую.

Можете добавить поддержку протокола QUIC?

Включение в конфиге:
`MODE_QUIC=1`

Аргументы запуска:
`NFQWS_OPT_DESYNC_QUIC="--dpi-desync=fake,disorder2 --dpi-desync-repeats=6 --dpi-desync-ttl=0  --dpi-desync-any-protocol --dpi-desync-cutoff=d4 --dpi-desync-fooling=md5sig,badsum"`

Взято из статьи на хабре: https://habr.com/ru/articles/834826

**Comment by Anonym-tsk** [comment]
А у вас без него не работает?

**Comment by RDL-28** [comment]
На компе и телевизорах работает, на телефоне лагает. Хочу проверить с протоколом QUIC, вдруг с ним и телефон заработает.

**Comment by Anonym-tsk** [comment]
Вы можете просто заблокировать QUIC в межсетевом экране кинетика, эффект будет тот же. Почти уверен, что это ни на что не повлияет

**Comment by Anonym-tsk** [comment]
Если вы заблокируете QUIC, ютуб не будет его использовать.
Если с заблокированным QUIC у вас ничего не работает, то и с модификацией udp пакетов ничего не изменится.

**Comment by Anonym-tsk** [comment]
Поддержка QUIC добавлена. Можно переустановить и проверить.

**Comment by ops244** [comment]
вот и инстаграм заработал, а говорили блок по ip...
