### ISSUE TITLE
После установки nfqws-keenetic 2.4.1 роутер дважды ушёл в перезагрузку в течение 20 минут

### ISSUE THREAD

**Issue by Seamas73** [Anonym-tsk/nfqws-keenetic#86]
Скачал на Keenetic Giga (KN-1011) пакет nfqws-keenetic_2.4.1_mipsel-3.4.ipk, положил его в /opt/root на флешке с Entware, запустил установку: ```opkg install /opt/root/nfqws-keenetic_2.4.1_mipsel-3.4.ipk```, затем остановил сервис и чуть подправил nfqws.conf и S51nfqws (у меня IPv6 через 6in4-туннель, так что я добавил в конфиг  переменную ```ISP_INTERFACE6``` и соответственно изменил скрипт автозапуска).
После повторного запуска скрипта роутер через пару минут ушёл в перезагрузку, а потом ещё минут через 15 ещё раз перезагрузился. Так как ничего в роутере не менял, а только проапгрейдил nfqws с версии 2.3.3 на версию 2.4.1, логично предположить, что роняет роутер именно nfqws с новыми настройками. Я остановил сервис и удалил пакет nfqws-keenetic и роутер больше не перезагружается.
К сожалению, логов ошибки предоставить не могу: syslog-ng я пару недель назад остановил, чтобы не слишком насиловать флешку, в конфиге nfqws значение переменной ```LOG_LEVEL``` было выставлено в 0, а информация в логе роутера сохраняется только с момента старта. 
Пока вернусь на версию 2.3.3: ютуб, вроде, работает, заблокированные РКН сайты открываются, а дискордом я не пользуюсь.

**Comment by Anonym-tsk** [comment]
Обновите роутер с предварительно канала до версии 4.2.1
И не надо ничего править в скриптах, оно и так работает с 6in4

**Comment by Seamas73** [comment]
Вы правы, на прошивке 4.2.1 роутер при работе nfqws-keenetic v.2.4.1 не перезагружается.
