### ISSUE TITLE
[BUG] Не работает ручная установка

### ISSUE THREAD

**Issue by warez4me** [Anonym-tsk/nfqws-keenetic#9]
Попытка ручной установки выдает ошибку
git: 'remote-htps' is not a git command. See 'git --help'.
The most similar command is
        remote-https

Первоначальный вариант был установлен вручную без проблем, 
затем так же вручную удален по инструкции автора.

**Comment by Anonym-tsk** [comment]
Entware установлен на внутреннюю память или на USB?
Пакет git-http установился? (Если используете внутреннюю память, он бывает падает при установке из-за того, что не хватает места)

**Comment by warez4me** [comment]
Entware стоит на флешке.
Как проверить , установлен ли корректно git-http ?
Смущает текст самой ош. команды 'remote-htps'
htps - это что?
Я подумал, что где-то в скрипте описка.

**Comment by Anonym-tsk** [comment]
Сделать opkg install git-http
Проверить ручную установку.
Подозреваю, вы просто где-то отпечатались или скопировали команду не полностью

**Comment by warez4me** [comment]
Ладно, если это точно не у вас, пока не буду дергаться - заработало, и ладно.
Если в будущем нарвусь на эти грабли, буду разбираться.

**Comment by Anonym-tsk** [comment]
Проверил еще раз инструкцию - ошибок нет, все работает.
```
~ # opkg install git git-http curl
Installing git (2.45.2-2) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/git_2.45.2-2_mipsel-3.4.ipk
Installing git-http (2.45.2-2) to root...
Downloading http://bin.entware.net/mipselsf-k3.4/git-http_2.45.2-2_mipsel-3.4.ipk
Package curl (8.8.0-2) installed in root is up to date.
Configuring git.
Configuring git-http.
~ #
~ # git clone https://github.com/Anonym-tsk/nfqws-keenetic.git --depth 1
Cloning into 'nfqws-keenetic'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 26 (delta 0), reused 16 (delta 0), pack-reused 0
Receiving objects: 100% (26/26), 9.77 KiB | 526.00 KiB/s, done.
~ #
~ # chmod +x ./nfqws-keenetic/*.sh
```
