### ISSUE TITLE
[BUG] Ломается nfqws с версии 2.5.1

### ISSUE THREAD

**Issue by detrinatiya** [Anonym-tsk/nfqws-keenetic#98]
**Опишите проблему**
После обновления на 2.5.3 с 2.4.2 перестал работать nfqws. На 2.5.1 данный баг проявляется после нескольких перезагрузок. После перезагрузок на 2.5.x появляются ошибки kernel:
```
ra = 0040ef10 in
epc = 0040ef58 in
do_page_fault(): sending SIGSEGV to nfqws for invalid read access from 00000006
```
Переустановка Entware не помогла, помогает только даунгрейд до 2.4.2.

**Модель маршрутизатора**
Keenetic Omni (KN-1410), KeeneticOS 4.2.1

**Провайдер**
beeline Ethernet

**Выполните команды и приложите их вывод**
`opkg info nfqws-keenetic`
```
Package: nfqws-keenetic
Version: 2.5.3
Depends: iptables, busybox
Conflicts: tpws-keenetic
Status: install user installed
Section: net
Architecture: mipsel-3.4
Conffiles:
 /opt/etc/nfqws/nfqws.conf fbb16b924528e98ea13e1ccfab14c19c5a66b394aa2f861feee41ca143aeab27
/opt/etc/nfqws/user.list 45dc2adaa172b86d73369c6ed12a8a0e648b851b66293b11514c3b1d4bd3fce6
/opt/etc/nfqws/auto.list e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
/opt/etc/nfqws/exclude.list 56674d7bd42a36480737a298a514620f0d3a8151e8e93a8b7defb3b2161b0513
```

`/opt/etc/init.d/S51nfqws restart`
```
Service NFQWS is not running
we have 5 user defined desync profile(s) and default low priority profile 0
Loading hostlist /opt/etc/nfqws/user.list
loading plain text list
Loaded 13 hosts from /opt/etc/nfqws/user.list
Loading hostlist /opt/etc/nfqws/user2.list
loading plain text list
Loaded 13 hosts from /opt/etc/nfqws/user2.list
Loading hostlist /opt/etc/nfqws/user3.list
loading plain text list
Loaded 9 hosts from /opt/etc/nfqws/user3.list
Loading hostlist /opt/etc/nfqws/user4.list
loading plain text list
Loaded 9 hosts from /opt/etc/nfqws/user4.list
Started NFQWS service
```

`cat /opt/etc/nfqws/nfqws.conf`
```
С дефолтным конфигом баг проявляется, проблема точно не в нём
```

`ps | grep nfqws`
```
  977 nobody     680 S    /opt/usr/bin/nfqws --daemon --pi...
```

`iptables-save | grep 200`
```
-A POSTROUTING -o eth2.2 -p tcp -m tcp --dport 443 -m connbytes --connbytes 1:8 --connbytes-mode packets --connbytes-dir original -m mark ! --mark 0x40000000/0x40000000 -j NFQUEUE --queue-num 200 --queue-bypass
```

`sysctl net.netfilter.nf_conntrack_checksum`
```
net.netfilter.nf_conntrack_checksum = 0
```

**Comment by opodryadov** [comment]
> Переустановка Entware не помогла, помогает только даунгрейд до 2.4.2.

Аналогичная проблема. Решилась также даунгрейдом.

**Comment by LordSlon** [comment]
я предположу, что ломается из-за неправильно прописанного eth. Раньше стояло eth2.2 все работало (я так и оставил), сейчас прописывает eth3. Keenetic Hopper KN-3810

**Comment by kotovasia5120** [comment]
> я предположу, что ломается из-за неправильно прописанного eth. Раньше стояло eth2.2 все работало (я так и оставил), сейчас прописывает eth3. Keenetic Hopper KN-3810


помогло вроде
