### ISSUE TITLE
[BUG] nfqws web, большие списки не грузятся

### ISSUE THREAD

**Issue by Omn1z** [Anonym-tsk/nfqws-keenetic#99]
2ух метровый список не отображается (2 097 152 bytes)
![{320A25C2-9962-42E5-90A5-7E66229C4832}](https://github.com/user-attachments/assets/5872202c-1ef3-4499-9daf-793f738de2b9)

**Comment by Anonym-tsk** [comment]
Прикрепите сюда список

**Comment by Omn1z** [comment]
[user.zip](https://github.com/user-attachments/files/17477587/user.zip)

**Comment by Xassewi** [comment]
![Uploading image.png…]()

**Comment by Xassewi** [comment]
твой лист вставился

**Comment by Anonym-tsk** [comment]
К сожалению, это ограничения встроенного веб-сервера.
Вы можете изменить конфигурацию php самостоятельно:
Откройте файл `/opt/etc/php.ini` и измените следующие значения
```
memory_limit = 32M
post_max_size = 32M
upload_max_filesize = 16M
```

**Comment by Xassewi** [comment]
Да помогло.

вт, 22 окт. 2024 г., 18:56 Nikolay Vasilchuk ***@***.***>:

**Comment by Omn1z** [comment]
Помогло, спасибо
